### ISSUE TITLE
php运行时出现了undefined symbol: conn_pool_disconnect_server错误

### ISSUE THREAD

**Issue by Luckyboys** [happyfish100/fastdfs#110]
已经下载最新的libfastcommon
然后

> ./make.sh clean
> ./make.sh
> ./make.sh install

然后再导fastdfs目录里面也是

> ./make.sh clean
> ./make.sh
> ./make.sh install

然后再到php_client目录

> make clean
> ./configure
> make
> make install

都很正常

但是运行php -v时，就会出现

> php: symbol lookup error: /usr/local/lib/libfdfsclient.so: undefined symbol: conn_pool_disconnect_server

错误

php是7.1.3

PHP 7.1.3 (cli) (built: Apr 12 2017 15:39:02) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.3, Copyright (c) 1999-2017, by Zend Technologies
php: symbol lookup error: /usr/local/lib/libfdfsclient.so: undefined symbol: conn_pool_disconnect_server

**Comment by happyfish100** [comment]
可能安装了老版本的libfastcommon，需要删除一下，命令如下：
/bin/rm -rf /usr/local/lib/libfastcommon.so /usr/local/include/fastcommon

**Comment by Luckyboys** [comment]
真的好了~~谢谢鱼大大~~
