### ISSUE TITLE
执行make.sh的时候，报错：[tracker_client_thread.o] Error 1  && undefined reference to `fc_safe_read'

### ISSUE THREAD

**Issue by dadalgq** [happyfish100/fastdfs#123]
[root@localhost fastdfs]# ./make.sh 
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -o ../common/fdfs_global.o ../common/fdfs_global.c  -I../common -I/usr/include/fastcommon
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -o tracker_proto.o tracker_proto.c  -I../common -I/usr/include/fastcommon
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -o tracker_mem.o tracker_mem.c  -I../common -I/usr/include/fastcommon
tracker_mem.c: In function ?.racker_write_to_changelog?.
tracker_mem.c:251: warning: implicit declaration of function ?.c_safe_write?
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -o tracker_service.o tracker_service.c  -I../common -I/usr/include/fastcommon
In file included from /usr/include/fastcommon/fast_task_queue.h:19,
                 from tracker_nio.h:17,
                 from tracker_service.c:34:
/usr/include/fastcommon/ioevent.h:82:2: error: #error port me
/usr/include/fastcommon/ioevent.h:95:2: error: #error port me
/usr/include/fastcommon/ioevent.h:108:2: error: #error port me
tracker_service.c: In function ?.racker_changelog_response?.
tracker_service.c:513: warning: implicit declaration of function ?.c_safe_read?
tracker_service.c: In function ?.racker_deal_server_list_all_groups?.
tracker_service.c:2989: warning: implicit declaration of function ?.ree_queue_set_buffer_size?
make: *** [tracker_service.o] Error 1
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -o ../tracker/fdfs_shared_func.o ../tracker/fdfs_shared_func.c  -I. -Itrunk_mgr -I../common -I../tracker -I../client -Ifdht_client -I/usr/include/fastcommon
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -o tracker_client_thread.o tracker_client_thread.c  -I. -Itrunk_mgr -I../common -I../tracker -I../client -Ifdht_client -I/usr/include/fastcommon
In file included from /usr/include/fastcommon/fast_task_queue.h:19,
                 from tracker_client_thread.c:28:
/usr/include/fastcommon/ioevent.h:82:2: error: #error port me
/usr/include/fastcommon/ioevent.h:95:2: error: #error port me
/usr/include/fastcommon/ioevent.h:108:2: error: #error port me
make: *** [tracker_client_thread.o] Error 1
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -o ../common/fdfs_http_shared.o ../common/fdfs_http_shared.c  -I../common -I../tracker -I/usr/include/fastcommon
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -o ../common/mime_file_parser.o ../common/mime_file_parser.c  -I../common -I../tracker -I/usr/include/fastcommon
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -o ../storage/trunk_mgr/trunk_shared.o ../storage/trunk_mgr/trunk_shared.c  -I../common -I../tracker -I/usr/include/fastcommon
../storage/trunk_mgr/trunk_shared.c: In function ?.runk_file_get_content_ex?.
../storage/trunk_mgr/trunk_shared.c:435: warning: implicit declaration of function ?.c_safe_read?
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -o tracker_client.o tracker_client.c  -I../common -I../tracker -I/usr/include/fastcommon
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -o client_func.o client_func.c  -I../common -I../tracker -I/usr/include/fastcommon
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -o client_global.o client_global.c  -I../common -I../tracker -I/usr/include/fastcommon
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -o storage_client.o storage_client.c  -I../common -I../tracker -I/usr/include/fastcommon
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -fPIC -o ../common/fdfs_global.lo ../common/fdfs_global.c  -I../common -I../tracker -I/usr/include/fastcommon
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -fPIC -o ../common/fdfs_http_shared.lo ../common/fdfs_http_shared.c  -I../common -I../tracker -I/usr/include/fastcommon
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -fPIC -o ../common/mime_file_parser.lo ../common/mime_file_parser.c  -I../common -I../tracker -I/usr/include/fastcommon
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -fPIC -o ../tracker/tracker_proto.lo ../tracker/tracker_proto.c  -I../common -I../tracker -I/usr/include/fastcommon
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -fPIC -o ../tracker/fdfs_shared_func.lo ../tracker/fdfs_shared_func.c  -I../common -I../tracker -I/usr/include/fastcommon
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -fPIC -o ../storage/trunk_mgr/trunk_shared.lo ../storage/trunk_mgr/trunk_shared.c  -I../common -I../tracker -I/usr/include/fastcommon
../storage/trunk_mgr/trunk_shared.c: In function ?.runk_file_get_content_ex?.
../storage/trunk_mgr/trunk_shared.c:435: warning: implicit declaration of function ?.c_safe_read?
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -fPIC -o tracker_client.lo tracker_client.c  -I../common -I../tracker -I/usr/include/fastcommon
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -fPIC -o client_func.lo client_func.c  -I../common -I../tracker -I/usr/include/fastcommon
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -fPIC -o client_global.lo client_global.c  -I../common -I../tracker -I/usr/include/fastcommon
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -c -fPIC -o storage_client.lo storage_client.c  -I../common -I../tracker -I/usr/include/fastcommon
cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -o fdfs_monitor fdfs_monitor.c  ../common/fdfs_global.o ../common/fdfs_http_shared.o ../common/mime_file_parser.o ../tracker/tracker_proto.o ../tracker/fdfs_shared_func.o ../storage/trunk_mgr/trunk_shared.o tracker_client.o client_func.o client_global.o storage_client.o -L/usr/lib64 -lpthread -lfastcommon -I../common -I../tracker -I/usr/include/fastcommon
../storage/trunk_mgr/trunk_shared.o: In function `trunk_file_do_lstat_func_ex':
/opt/fastdfs/client/../storage/trunk_mgr/trunk_shared.c:629: undefined reference to `fc_safe_read'
../storage/trunk_mgr/trunk_shared.o: In function `trunk_file_get_content_ex':
/opt/fastdfs/client/../storage/trunk_mgr/trunk_shared.c:435: undefined reference to `fc_safe_read'
collect2: ld returned 1 exit status
make: *** [fdfs_monitor] Error 1

**Comment by dadalgq** [comment]
使用的是5.10版本的tar.gz，解压后执行的./make.sh

**Comment by happyfish100** [comment]
libfastcommon版本太旧的缘故，请使用 github上的最新版本。

**Comment by dadalgq** [comment]
@happyfish100 但是https://github.com/happyfish100/libfastcommon 的tag或者release并没有比1.0.7更新的了，难道我要clone下来master，然后打包成tar.gz直接丢到服务器下去install？

**Comment by dadalgq** [comment]
直接将master 打包成tar.gz install 后OK！
