### ISSUE TITLE
文档官网 挂了 请求支持

### ISSUE THREAD

**Issue by xcorpio** [happyfish100/fastdfs#145]
想看些文档，网址打不开了
http://www.csource.org/

**Comment by vipcxj** [comment]
好久以前就挂了，完全不知道哪里还有所谓的官方文档~

**Comment by Gmle7** [comment]
我也想知道，文档怎么没了？可以直接放到GitHub上吧

**Comment by fluffywar** [comment]
没有网站了，给个论坛地址也成。

**Comment by yangyh22** [comment]
这个官网文档都没有的 fastDfs 作者还在维护吗？或者有什么其他的推荐？

**Comment by RocFang** [comment]
http://bbs.chinaunix.net/forum-240-1.html

官网一直是这个，之前http://www.csource.org/也是跳转到这里的，你们去看吧。

**Comment by wswind** [comment]
#187
