### ISSUE TITLE
fdfs storage ip是否支持自定义

### ISSUE THREAD

**Issue by rom4j** [happyfish100/fastdfs#198]
fdfs storage ip自动获取的方式可以设置么?现在单机docker想运行,但是又分配不到更多的ip,只能获得(172.0.0.2)。宿主机访问不到

**Comment by jinghuaz** [comment]
是的 遇到一样的问题

**Comment by thisisrui** [comment]
可以通过 iptables nat 表转发解决： [原因及解决](https://github.com/happyfish100/fastdfs/issues/491#issuecomment-822945303)
