### ISSUE TITLE
/usr/lib64/libfastcommon.so：对‘cos’未定义的引用

### ISSUE THREAD

**Issue by lext-7** [happyfish100/fastdfs#20]
从github克隆的源文件，安装了libfastcommon和libevent-2.0.1
运行sudo ./make.sh就会曝出下面的错误
```
    cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -o fdfs_monitor fdfs_monitor.c  ../common/fdfs_global.o ../common/fdfs_http_shared.o ../common/mime_file_parser.o ../tracker/tracker_proto.o ../tracker/fdfs_shared_func.o ../storage/trunk_mgr/trunk_shared.o tracker_client.o client_func.o client_global.o storage_client.o -L/usr/lib64 -lpthread -ldl -rdynamic -lfastcommon -I../common -I../tracker -I/usr/include/fastcommon
    /usr/lib64/libfastcommon.so：对‘cos’未定义的引用
    /usr/lib64/libfastcommon.so：对‘sqrt’未定义的引用
    collect2: error: ld returned 1 exit status
    make: *** [fdfs_monitor] 错误 1
```

**Comment by chuandadexiaoyu** [comment]
同样遇到了这个问题，看来需要自己去排查了

**Comment by lext-7** [comment]
我从googlecode export到自己的github，然后从自己的github下载源码安装就没问题。。。

**Comment by chuandadexiaoyu** [comment]
额，fastDFS和libcommon 的源码地址贴一下；
我觉着问题应该是编译shared_func.c的时候需要加上-lm

**Comment by chuandadexiaoyu** [comment]
作者最新的一次提交
git show ba6cc38703800157a4b6c923e8d0238b6be9fcca

在libfastcommon   src/shared_func.c   2096行  get_line_distance_km这个方法，
用到了 cos sqrt两个math方法，censtos编译shared_func.c的时候，需要加上 -lm；

可能作者当时的环境是mac吧，不需要-lm    :-(

**Comment by lext-7** [comment]
https://github.com/lext-7/fastdfs/
这个直接编译没问题，亲测有效

**Comment by chuandadexiaoyu** [comment]
额，那是因为你用的libcommon和fastDFS都是旧的版本......
代码里面还没有用到get_line_distance_km这个方法

**Comment by happyfish100** [comment]
你们动作真快，获取了一个中间版本。
后来解决了这个问题，下载最新版本用 ./make.sh重新编译吧。
