### ISSUE TITLE
用java客户端下载1.14G文件报堆栈溢出

### ISSUE THREAD

**Issue by PointerWild** [happyfish100/fastdfs#210]
报错如下：
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.csource.fastdfs.ProtoCommon.recvPackage(ProtoCommon.java:256)
	at org.csource.fastdfs.StorageClient.download_file(StorageClient.java:1301)
	at org.csource.fastdfs.StorageClient1.download_file1(StorageClient1.java:655)
	at org.csource.fastdfs.StorageClient1.download_file1(StorageClient1.java:636)
	at Analysis.Extract.FastDFSud.download_file(FastDFSud.java:149)
	at Analysis.Extract.FastDFSud.downloadFile(FastDFSud.java:182)

配置情况：
jdk 1.8
windows server 2008R2   1T/16G
eclipse中已经设置了最大内存 2.2G (-Xmx2400M)

能麻烦帮忙解决一下吗？

定位代码段如下：

1：//atAnalysis.Extract.FastDFSud.download_file(FastDFSud.java:149) 
`   /** 
     * 文件下载到磁盘 
     * @param path 图片路径 
     * @param output 输出流 中包含要输出到磁盘的路径 
     * @return -1失败,0成功 
     */  
    public int download_file(String path,BufferedOutputStream output) {  
        //byte[] b = storageClient.download_file(group, path);  
        int result=-1;  
        try {  
//atAnalysis.Extract.FastDFSud.download_file(FastDFSud.java:149)  此处下行
            byte[] b = storageClient.download_file1(path);  
                try{  
                    if(b != null){  
                        output.write(b);  
                        result=0;  
                    }  
                }catch (Exception e){} //用户可能取消了下载  
                finally {  
                    if (output != null)  
                        try {  
                            output.close();  
                        } catch (IOException e) {  
                            e.printStackTrace();  
                        }  
            }  
        } catch (Exception e) {  
            e.printStackTrace();  
        }  
        return result;  
    }  `

2：at Analysis.Extract.FastDFSud.downloadFile(FastDFSud.java:182)
`   /** 
     * 文件下载到磁盘 
     * @param groupID 图片路径 
     * @param localPath 下载到本地的地址(输出流中包含要输出到磁盘的路径 )
     * @return -1失败,0成功 
     */
    public int downloadFile(String groupID ,String localPath) 
    {
    	int result = -1;
    	try {
    		 FileOutputStream fos=new FileOutputStream(localPath);
             BufferedOutputStream bos=new BufferedOutputStream(fos);
//at Analysis.Extract.FastDFSud.downloadFile(FastDFSud.java:182) 此处下行
             result = download_file(groupID,bos);
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
			
			 return result;
		}
    	
         return result;
    }`

**Comment by PointerWild** [comment]
1：//atAnalysis.Extract.FastDFSud.download_file(FastDFSud.java:149) 
/** 
     * 文件下载到磁盘 
     * @param path 图片路径 
     * @param output 输出流 中包含要输出到磁盘的路径 
     * @return -1失败,0成功 
     */  
    public int download_file(String path,BufferedOutputStream output) {  
        //byte[] b = storageClient.download_file(group, path);  
        int result=-1;  
        try {  
////atAnalysis.Extract.FastDFSud.download_file(FastDFSud.java:149)  此处下一行是报错位置
            byte[] b = storageClient.download_file1(path);  
                try{  
                    if(b != null){  
                        output.write(b);  
                        result=0;  
                    }  
                }catch (Exception e){} //用户可能取消了下载  
                finally {  
                    if (output != null)  
                        try {  
                            output.close();  
                        } catch (IOException e) {  
                            e.printStackTrace();  
                        }  
            }  
        } catch (Exception e) {  
            e.printStackTrace();  
        }  
        return result;  
    }  


2：at Analysis.Extract.FastDFSud.downloadFile(FastDFSud.java:182)  
 /** 
     * 文件下载到磁盘 
     * @param groupID 图片路径 
     * @param localPath 下载到本地的地址(输出流中包含要输出到磁盘的路径 )
     * @return -1失败,0成功 
     */
    public int downloadFile(String groupID ,String localPath) 
    {
    	int result = -1;
    	try {
    		 FileOutputStream fos=new FileOutputStream(localPath);
             BufferedOutputStream bos=new BufferedOutputStream(fos);
//at Analysis.Extract.FastDFSud.downloadFile(FastDFSud.java:182)   此处下一行是报错位置
             result = download_file(groupID,bos);
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
			
			 return result;
		}
    	
         return result;
    }

**Comment by Succy** [comment]
给你两个建议：
+ 使用分片下载，fdfs的java客户支持一次下载一部分，具体参考这个方法：` public byte[] download_file(String group_name, String remote_filename, long file_offset, long download_bytes) ` 分片下到本地之后，然后合并成一个完整的文件。
+ 采用堆外内存映射处理，避免OOM

**Comment by leewill0211** [comment]
fdfsjava客户端里提供的另外两个方法可能会满足你的需求：
1. 直接下载到本地文件
```
  public int download_file1(String file_id, String local_filename) throws IOException, MyException {
    final long file_offset = 0;
    final long download_bytes = 0;

    return this.download_file1(file_id, file_offset, download_bytes, local_filename);
  }
```

2. 通过回调接口将下载的小数据段写入流中
```
  public int download_file1(String file_id, DownloadCallback callback) throws IOException, MyException {
    final long file_offset = 0;
    final long download_bytes = 0;

    return this.download_file1(file_id, file_offset, download_bytes, callback);
  }
```

**Comment by PointerWild** [comment]
谢谢，根据您俩的提示，已经可以下载2.7G的文件，谢谢
