### ISSUE TITLE
根据wiki搭建的集群环境，短时间文件无法访问

### ISSUE THREAD

**Issue by shan165310175** [happyfish100/fastdfs#251]
1.上传文件后，使用fastdfs-client立即下载，出现无法找到文件。
2.如果sleep几秒，等文件同步完成后，下载文件就没有问题。

2.上传文件后，立即使用HTTP方式访问文件，出现404，但是如果过一会儿，文件可以访问。

文件是20M大小的。

请问下这种情况该如何处理。

**Comment by shan165310175** [comment]
3个tracker, 3个storage相互同步备份的。

**Comment by fizzzzzz** [comment]
我这边也有这种问题

**Comment by shan165310175** [comment]
> 我这边也有这种问题

使用NGINX方式访问就没有问题了哦。
但是使用fastdfs-client-java提供的api在短时间访问就有问题。
同一个连接没有问题，不同连接就有问题。

**Comment by retamia** [comment]
你好请问你那边解决这问题了吗， 我这边还发现 fdfs_download_file 这条命令行有时候会出现文件找不到的情况。通过日志发现文件是在9这台服务器上，但是会去13这台服务器去下载。
![image](https://user-images.githubusercontent.com/9671597/57520577-9374e400-7350-11e9-9a2f-2db3e35bf92f.png)

**Comment by shan165310175** [comment]
> 你好请问你那边解决这问题了吗， 我这边还发现 fdfs_download_file 这条命令行有时候会出现文件找不到的情况。通过日志发现文件是在9这台服务器上，但是会去13这台服务器去下载。
> ![image](https://user-images.githubusercontent.com/9671597/57520577-9374e400-7350-11e9-9a2f-2db3e35bf92f.png)

安装nginx即可，通过nginx访问。
