### ISSUE TITLE
PHP7可以安装fastdfs_client扩展吗？

### ISSUE THREAD

**Issue by mirrorgdit** [happyfish100/fastdfs#256]
我的服务器环境有一个PHP5.4的版本，已经成功安装好fastdfs扩展，也正常在使用，现在服务器多了个PHP7版本，但是安装fastdfs扩展的时候报以下错误：

root/FastDFS/php_client/fastdfs_client.c: 在函数‘fastdfs_convert_metadata_to_array’中:
/root/FastDFS/php_client/fastdfs_client.c:225: 错误：传递‘zend_hash_get_current_data_ex’的第 2 个参数时在不兼容的指针类型间转换
/usr/local/php7/include/php/Zend/zend_hash.h:205: 附注：需要类型‘HashPosition *’，但实参的类型为‘void **’
/root/FastDFS/php_client/fastdfs_client.c:225: 错误：提供给函数‘zend_hash_get_current_data_ex’的实参太多

**Comment by aLoNeIT** [comment]
可以安装的，我们就是PHP7+，安装一切正常~~按照readme看即可

**Comment by mirrorgdit** [comment]
> 可以安装的，我们就是PHP7+，安装一切正常~~按照readme看即可

我的服务器有多个PHP版本，其中5.4版本安装正常，但是php7的版本安装总是报错
root/FastDFS/php_client/fastdfs_client.c: 在函数‘fastdfs_convert_metadata_to_array’中:
/root/FastDFS/php_client/fastdfs_client.c:225: 错误：传递‘zend_hash_get_current_data_ex’的第 2 个参数时在不兼容的指针类型间转换
/usr/local/php7/include/php/Zend/zend_hash.h:205: 附注：需要类型‘HashPosition *’，但实参的类型为‘void **’
/root/FastDFS/php_client/fastdfs_client.c:225: 错误：提供给函数‘zend_hash_get_current_data_ex’的实参太多

**Comment by happyfish100** [comment]
需要在php7环境下重新执行  phpize，./configure 等步骤。
怀疑是php不同版本部署在同一台机器上，把环境搞乱了。
比如，你需要确认  phpize是php7自带的，而不是php5的。

**Comment by mirrorgdit** [comment]
> 
> 
> 需要在php7环境下重新执行 phpize，./configure 等步骤。
> 怀疑是php不同版本部署在同一台机器上，把环境搞乱了。
> 比如，你需要确认 phpize是php7自带的，而不是php5的。
