### ISSUE TITLE
allow_hosts 不支持阿里云SLB健康检查地址网段 100.64.0.0/10

### ISSUE THREAD

**Issue by ackfin** [happyfish100/fastdfs#292]
要用阿里云SLB对tracker做负载均衡和健康检查，但tracker allow_hosts不支持阿里云SLB健康检查地址网段 100.64.0.0/10
参考： [7. HTTP监听向后端ECS实例执行健康检查的IP地址是什么？](https://help.aliyun.com/knowledge_detail/55205.html)
配置：
```
allow_hosts=10.2.14.0/23
allow_hosts=100.64.0.0/10 
```

```
[2019-05-22 21:52:25] ERROR - file: shared_func.c, line: 1620, ip address: 100.64.0.0/10, invalid network bits: 10, it should >= 16 and < 32
[2019-05-22 21:52:25] CRIT - exit abnormally!
```

**Comment by happyfish100** [comment]
100.64.0.0/10 这个写法有问题，你试试 100.64.0.0/16

**Comment by happyfish100** [comment]
100.64.0.0/10配置没问题，就是IP空间太大了。之前限制网络位数必须大于等于16，是担心allow_hosts中的IP地址展开后太大，占用过多的内存空间。我把限制改下，改为必须大于等于10好了。

**Comment by happyfish100** [comment]
已经修复了。下载最新的libfastcommon重新编译和安装即可。

**Comment by ackfin** [comment]
@happyfish100 好的，谢谢

**Comment by ackfin** [comment]
更新 libfastcommon 后，测试可以正常添加 allow_hosts=100.64.0.0/10 配置，问题解决。谢谢。
