### ISSUE TITLE
您好，测试上传失败，报这个错误，看了storage配置路径没有问题！

### ISSUE THREAD

**Issue by redjiang** [happyfish100/fastdfs#293]
ERROR - file: tracker_proto.c, line: 48, server: 192.168.14.36:22122, response status 2 != 0
[2019-05-25 04:54:50] ERROR - file: ../client/tracker_client.c, line: 907, fdfs_recv_response fail, result: 2
tracker_query_storage fail, error no: 2, error info: No such file or directory

**Comment by cocosip** [comment]
ps -ef| grep fdfs 看下tracker跟storage 是不是都正常的跑起来了

**Comment by redjiang** [comment]
@cocosip 您好，非常感谢，问题我已经解决了，我用的虚拟机nat模式，在这个模式下不可以，换成桥接后好了！
