### ISSUE TITLE
storage目录建立在映射盘上，导致free storage为负数，从而无法上传文件

### ISSUE THREAD

**Issue by developer-yemin** [happyfish100/fastdfs#297]
df -h的结果为
------------------------------------------------
文件系统 容量 已用 可用 已用% 挂载点
/dev/mapper/centos-root 36G 6.2G 29G 18% /
devtmpfs 16G 0 16G 0% /dev
tmpfs 16G 0 16G 0% /dev/shm
tmpfs 16G 42M 16G 1% /run
tmpfs 16G 0 16G 0% /sys/fs/cgroup
/dev/vda1 1014M 209M 806M 21% /boot
tmpfs 3.2G 8.0K 3.2G 1% /run/user/42
tmpfs 3.2G 32K 3.2G 1% /run/user/0
10.136.65.236:/zgyd2 4.3P 200T 3.3P 6% /mnt
------------------------------------------------------
storage的路径在建立在/mnt上，映射的一个网盘，4.3P，已经上传了18G的文件。现在上传失败，错误信息是errno 28 not enough space. 运行monitor查看storage情况，发现free storage为负数。
id = 10.136.32.106
ip_addr = 10.136.32.100 (oss-001) ACTIVE
http domain =
version = 5.11
join time = 2019-05-01 18:36:45
up time =
total storage = 284219904 MB
free storage = -817213645 MB
请问这种情况如何解决，tracker.conf中的reserved_storage_space设成0可以吗？我设成0貌似也没解决问题。谢谢。

**Comment by developer-yemin** [comment]
df -h的结果为
文件系统                 容量  已用  可用 已用% 挂载点
/dev/mapper/centos-root   36G  6.2G   29G   18% /
devtmpfs                  16G     0   16G    0% /dev
tmpfs                     16G     0   16G    0% /dev/shm
tmpfs                     16G   42M   16G    1% /run
tmpfs                     16G     0   16G    0% /sys/fs/cgroup
/dev/vda1               1014M  209M  806M   21% /boot
tmpfs                    3.2G  8.0K  3.2G    1% /run/user/42
tmpfs                    3.2G   32K  3.2G    1% /run/user/0
10.136.65.236:/zgyd2     4.3P  200T  3.3P    6% /mnt
storage的路径在建立在/mnt上，映射的一个网盘，4.3P，已经上传了18G的文件。现在上传失败，错误信息是errno 28 not enough space. 运行monitor查看storage情况，发现free storage为负数。
---------------------------------------------------------
 id = 10.136.32.106
                ip_addr = 10.136.32.100 (oss-001)  ACTIVE
                http domain =
                version = 5.11
                join time = 2019-05-01 18:36:45
                up time =
                total storage = 284219904 MB
                free storage = -817213645 MB
---------------------------------------------------------
请问这种情况如何解决，tracker.conf中的reserved_storage_space设成0可以吗？我设成0貌似也没解决问题。谢谢。

**Comment by developer-yemin** [comment]
typedef struct
{
	int total_mb; //total spaces
	int free_mb;  //free spaces
} FDFSStorePathInfo;

这个定义中的两个int类型是否应该改为int64_t，尤其是现在的磁盘空间大小已经超过了2,147,483,647。

**Comment by zhangjijian111** [comment]
同问  这个问题解决了吗?

**Comment by happyfish100** [comment]
刚修复了，获取 master代码即可。
