### ISSUE TITLE
是不是不支持 php7.3，我添加扩展了加载不了

### ISSUE THREAD

**Issue by chendaye** [happyfish100/fastdfs#304]
是不是不支持 php7.3，我添加扩展了加载不了

**Comment by wwc543198585** [comment]
兄弟有试过php7.1/7.2吗？支持不支持的，我看简介里面就写了个7.0

**Comment by chendaye** [comment]
7.2 试了 不成功

**Comment by chendaye** [comment]
![image](https://user-images.githubusercontent.com/22893123/59906056-49484d80-943a-11e9-98f3-31b3da2599d5.png)

**Comment by chendaye** [comment]
![image](https://user-images.githubusercontent.com/22893123/59906094-6a10a300-943a-11e9-9bee-766ffb0a0109.png)
![image](https://user-images.githubusercontent.com/22893123/59906134-8a406200-943a-11e9-9567-f32cb6dd3890.png)

**Comment by chendaye** [comment]
已经搞了快2天了，这是个大坑

**Comment by wwc543198585** [comment]
我就试了7.0可以运行，其他的版本还没时间去验证，￣□￣｜｜

**Comment by chendaye** [comment]
兄弟加一下qq或者微信 聊聊

**Comment by chendaye** [comment]
834261743

**Comment by chendaye** [comment]
已解决
