### ISSUE TITLE
 ===谢谢大哥=== 帮忙给看看[2019-09-06 03:12:25] ERROR - file: storage_ip_changed_dealer.c, line: 180, connect to tracker server 172.16.22.188:22122 fail, errno: 111, error info: Connection refused

### ISSUE THREAD

**Issue by shiboyang** [happyfish100/fastdfs#325]
2个问题 
1. 在docker中安装了/season/fastdfs 然后就是根据 https://hub.docker.com/r/season/fastdfs配置的然后storage一直报链接超时，后来换成了把storage启动命令改用自己的ip地址 然后替换了fdfs-config里面的storage.conf文件的tracker-server-ip就拒绝链接
2 在tracker和strage里面不能安装vim vi 而且不能update 替换软件源也无效

===谢谢大哥===
帮忙给看看

**Comment by shiboyang** [comment]
补充一点 在mac环境下

**Comment by longxishui** [comment]
没人吗
