### ISSUE TITLE
storage修改端口重启后，就一直处于Offline

### ISSUE THREAD

**Issue by hgllyppl** [happyfish100/fastdfs#342]
storage日志如下
ERROR - file: tracker_proto.c, line: 49, server: 172.17.245.79:22122, response status 22 != 0
ERROR - file: tracker_client_thread.c, line: 1998, fdfs_recv_response fail, result: 22
集群是2个tracker、2个group，每个group一个storage，我改了其中一个storage的端口重启后，这个storage就一直处于offline呢，请问下鱼大，这是什么情况？

**Comment by happyfish100** [comment]
同组内的storage server端口需要保持一致。

**Comment by hgllyppl** [comment]
> 同组内的storage server端口需要保持一致。
不不不，我是2个group，每个group只有一个storage，我改了其中一个group的storage的端口，然后它就一直是offline了，
另外在请教一个问题，同一个ip上只能启动一个storage吗，我再在这个ip上启动一个不同端口的storage，通过fdfs_monitor只能看到后启动的storage处于active，另外一个是看不到的？

**Comment by happyfish100** [comment]
同一台服务器可以部署多个storage server。
应该是报错了，你分别看下tracker 和 storage 日志文件。

**Comment by hgllyppl** [comment]
没有错误日志，也没有其他日志输出
我运行的两个docker容器，网络用的宿主机，其中一个docker同时跑tracker和storage，另外一个docker只跑storage，用fdfs_monitor监控看到情况就像是一个storage把另一个storage挤下去了，无论怎么重启storage，始终只有一个storage在线

**Comment by hgllyppl** [comment]
这几天又重新试了几把，关于端口的问题，如鱼大所说，同组内的端口必须保持一致，虽然我的demo是两个group，改了其中一个group storage的端口重启后就不能上线，那是因为改的那个组内还有一台已经下线的storage，这就导致了同组内的storage端口不一致

**Comment by hgllyppl** [comment]
关于第二个问题，还是没能得到解决，同一个ip上，网络用host的模式跑了3个docker，一个docker用作tracker，另外两个docker用作storage，如果两个storage跑在同一个group上，则只有一个能上线，另外一个正常启动无错误日志，如果两个storage跑在不同的group上，则都能上线

**Comment by hgllyppl** [comment]
第二个问题也解决了，第二个问题还是第一个问题的延续，因为用的宿主机的IP，所以每个storage必然使用的是不同的端口，如果两个storage跑不同的group还好，跑相同的group必然因为端口不一致起不来
