### ISSUE TITLE
ubuntu nginx make报错

### ISSUE THREAD

**Issue by WhatIsGhost** [happyfish100/fastdfs#350]
In file included from /usr/local/src/fastdfs-nginx-module/src//ngx_http_fastdfs_module.c:6:0:
/usr/local/src/fastdfs-nginx-module/src//common.c: In function ‘fdfs_mod_init’:
/usr/local/src/fastdfs-nginx-module/src//common.c:351:32: error: request for member ‘path’ in something not a structure or union
     g_fdfs_store_paths.paths[i].path);
                                ^
/usr/local/src/fastdfs-nginx-module/src//common.c:401:47: error: request for member ‘path’ in something not a structure or union
      group_store_paths[k].store_paths.paths[i].path);
                                               ^
/usr/local/src/fastdfs-nginx-module/src//common.c: In function ‘fdfs_http_request_handler’:
/usr/local/src/fastdfs-nginx-module/src//common.c:1088:42: error: request for member ‘path’ in something not a structure or union
      pStorePaths->paths[store_path_index].path, \
                                          ^
/usr/local/src/fastdfs-nginx-module/src//common.c:1433:41: error: request for member ‘path’ in something not a structure or union
     pStorePaths->paths[store_path_index].path, \
                                         ^
objs/Makefile:1205: recipe for target 'objs/addon/src/ngx_http_fastdfs_module.o' failed
make[1]: *** [objs/addon/src/ngx_http_fastdfs_module.o] Error 1
make[1]: Leaving directory '/usr/local/src/nginx-1.15.4'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by happyfish100** [comment]
你获取的master代码吧，需要使用FastDFS v6.03这个版本的。
我今天下午发布FastDFS v6.03好了。
我的锅，抱歉给你带来困扰了。

**Comment by WhatIsGhost** [comment]
恩，按照wiki里的文档来的，确实使用了master 后来我手动修改了common.c 删掉了 .path 可以编译了，一会儿我在多机试一下FastDFS v6.03这个版本
