### ISSUE TITLE
能否麻烦作者出一篇fastdfs的网络通信 解读扫盲文章,这样的话大家就可以使用各种语言实现客户端了

### ISSUE THREAD

**Issue by dushitaoyuan** [happyfish100/fastdfs#364]

**Comment by happyfish100** [comment]
之前在 ChinaUnix论坛整理过一篇英文版本的，我这两天可以整理一篇中文版本的通信协议发到微信公众号，供大家参考。你可以关注 FastDFS微信公众号，搜索 fastdfs 即可找到。

**Comment by dushitaoyuan** [comment]
已关注,大致看了下java client实现,命令中未看到关于连接维持的命令,之前使用5.11,无论 tracker和storage都是短连接形式,出现过连接达最大数问题,虽然后来通过增大连接数,和客户端及时关闭socket连接避免了这个问题,fdfs设计中是否存在hello包来实现池化storage scocket和tracker socket连接的机制?

**Comment by happyfish100** [comment]
微信公众号文章已发，我整理了大半天的网络通信协议，你可以看下。

**Comment by dushitaoyuan** [comment]
好的
