### ISSUE TITLE
storage如何删除多余的分组

### ISSUE THREAD

**Issue by muyline** [happyfish100/fastdfs#367]
在stroge设置了分组为group1,后来不想用这个group1，换成test。但是发现在storage_groups_new.dat里有2个分组，把data目录清空后重启后仍然还有。

**Comment by muyline** [comment]
/usr/bin/fdfs_monitor /etc/fdfs/client.conf delete group1 
提示Device or resource busy

**Comment by happyfish100** [comment]
需要将该group下的storage server删除后，才能删除group。

**Comment by muyline** [comment]
明白了先删除storage server
/usr/bin/fdfs_monitor /etc/fdfs/client.conf delete group1 x.x.xx
再删除分组
/usr/bin/fdfs_monitor /etc/fdfs/client.conf delete group1
