### ISSUE TITLE
请问fastdfs和nginx的关系

### ISSUE THREAD

**Issue by gzliudan** [happyfish100/fastdfs#373]
不安装nginx能否使用fastdfs？安装与不安装nginx有什么区别？

**Comment by tianmengwei110** [comment]
FastDFS通过Tracker服务器,将文件放在Storage服务器存储,但是同组之间的服务器需要复制文件,
有延迟的问题.假设Tracker服务器将文件上传到了A服务器,文件ID已经返回客户端,这时,后台会将
这个文件复制到B服务器,如果复制没有完成,客户端就用这个ID在B服务器取文件,肯定会出现错误。
这个fastdfs-nginx-module可以重定向连接到源服务器取文件,避免客户端由于复制延迟的问题,
出现错误。

**Comment by gzliudan** [comment]
谢谢

**Comment by HKcat2010** [comment]
> FastDFS通过Tracker服务器,将文件放在Storage服务器存储,但是同组之间的服务器需要复制文件,
> 有延迟的问题.假设Tracker服务器将文件上传到了A服务器,文件ID已经返回客户端,这时,后台会将
> 这个文件复制到B服务器,如果复制没有完成,客户端就用这个ID在B服务器取文件,肯定会出现错误。
> 这个fastdfs-nginx-module可以重定向连接到源服务器取文件,避免客户端由于复制延迟的问题,
> 出现错误。

请问现在“fastdfs-nginx-module”支持http协议直接上传nginx（比如直接用curl），再由nginx转存fdfs么？
