### ISSUE TITLE
求fastdfs各种错误码说明

### ISSUE THREAD

**Issue by muyline** [happyfish100/fastdfs#378]
如28是表示磁盘空间不足，其他的错误码说明能否提供一份。以备不时之需。。

**Comment by happyfish100** [comment]
看一下服务器上的 errno.h这个头文件即可。
可以通过 /usr/include/errno.h 找到。
比如Linux下最终的错误码头文件如下：
/usr/include/asm-generic/errno-base.h 
/usr/include/asm-generic/errno.h

**Comment by muyline** [comment]
OK。tks

**Comment by JellyBo** [comment]
这个28错误码我也是找了大半天，终于在这里找到的说明
