### ISSUE TITLE
一些问题想请教一下

### ISSUE THREAD

**Issue by WonderMing13** [happyfish100/fastdfs#379]
我们项目是使用FastDFS来进行小文件的上传和下载，所以有以下几点问题，希望大家看到可以帮帮我
1.上传速度是不是只有在提高的上行带宽这一种解决方案？
2.基于FastDFS如何针对用户来统计计算上传下载的流量?
不吝赐教

**Comment by martinzh717** [comment]
赶紧换吧 。 这软件没人维护。 有人回复也是ghost
