### ISSUE TITLE
ubuntu14.04 的安装问题

### ISSUE THREAD

**Issue by shangmin1990** [happyfish100/fastdfs#39]
os:ubuntu-server 14.04
libevent1.4.x 安装
libcommon安装成功
fastdfs编译通过

执行./make.sh install的时候报错
mkdir -p /usr/bin
mkdir -p /etc/fdfs
cp -f fdfs_trackerd /usr/bin
cp: cannot stat ‘fdfs_trackerd’: No such file or directory
make: *** [install] Error 1
mkdir -p /usr/bin
mkdir -p /etc/fdfs
cp -f fdfs_storaged  /usr/bin
cp: cannot stat ‘fdfs_storaged’: No such file or directory
make: *** [install] Error 1
mkdir -p /usr/bin
mkdir -p /etc/fdfs
mkdir -p /usr/lib64
cp -f fdfs_monitor fdfs_test fdfs_test1 fdfs_crc32 fdfs_upload_file fdfs_download_file fdfs_delete_file fdfs_file_info fdfs_appender_test fdfs_appender_test1 fdfs_append_file fdfs_upload_appender /usr/bin
if [ 0 -eq 1 ]; then cp -f libfdfsclient.a /usr/lib64; cp -f libfdfsclient.a /usr/lib;fi
if [ 1 -eq 1 ]; then cp -f libfdfsclient.so /usr/lib64; cp -f libfdfsclient.so /usr/lib;fi
cp: not writing through dangling symlink ‘/usr/lib/libfdfsclient.so’
make: *** [install] Error 1

安装过程问题不断各种google 终于到了这个错误就卡住了。。。
各位大侠帮忙看看吧 实在搞不定了 （顺便提一句 mac上安装4.x 版本也有问题 安装不成功 版本10.11.1 ，好像是同样的问题）

**Comment by shangmin1990** [comment]
init.d/里边有那两个文件 但是 storage和trackered文件夹下并没有那两个文件。。。

**Comment by shangmin1990** [comment]
问题已解决  本来想找个release的版本。后来发现于大大的release版本代码太落后了 代码全都更到master就没什么问题了。安装的时候可能仍会报错，自行google就可以解决的

**Comment by zhuyu1996** [comment]
？？？怎么解决的啊老哥

**Comment by alittlebitcool** [comment]
？？？怎么解决的啊老哥
