### ISSUE TITLE
关于Nginx的一些问题

### ISSUE THREAD

**Issue by Tdickson3** [happyfish100/fastdfs#401]
系统：`Debian10`
Nginx：`1.15.4/1.16.1`
安装步骤：

- `./configure --prefix=/usr/local/nginx --with-pcre=/root/soft/pcre-8.42 --with-openssl=/root/soft/openssl-1.1.1f --with-zlib=/root/soft/zlib-1.2.11 --add-module=/usr/local/src/fastdfs-nginx-module/src/`

- `make`

- `make install`

在编译安装Nginx 的时候加上`--add-module=/usr/local/src/fastdfs-nginx-module/src/`编译安装，可以成功启动，端口也是正常监听。但是无法访问。

浏览器访问的时候就是如下状态，一直转转转...

![image](https://user-images.githubusercontent.com/44915990/78899198-9e2b8200-7aa7-11ea-911d-db4389bad310.png)

**Comment by xiaodianku** [comment]
?

**Comment by xiaodianku** [comment]
怎么解决的？
