### ISSUE TITLE
获取storage外网ip的问题

### ISSUE THREAD

**Issue by shangmin1990** [happyfish100/fastdfs#42]
场景：服务器 amazon ec2 instance 1.
tracker与storager 都部署在这个实例上。
应用可以与Tracker通讯(client.conf 中指定tracker_server: shmin.net:22122)，tracker返回可以组信息，再返回一个可以用的storager。但是返回的可以用的storage ip是内网ip。Tracker、Storage间通过内网IP进行通讯，此时Tracker返回的是Storage的内网IP，导致应用无法根据返回的IP信息往Storage写入数据。
如何才能让应用获取到的是Storage的外网IP呢。尝试使用storager的bind-addr强制使用外网ip提供服务，再连接storager的时候又报can't create request错误。@happyfish100 请问这个问题应该怎么处理，tracker再返回可用storage信息的时候 ip 如何才能返回外网ip～～～

**Comment by wanghaolw** [comment]
我遇到相同的问题，事实上你在log里面看到的报错是可以忽略的，因为内网连不上的时候，会自动切换到公网，这时候你用fdfs_monitor 看一下 就会看到新加入的storage的状态已经变为同步中了

**Comment by shangmin1990** [comment]
@wanghaolw 会不会自动切换我具体还不太清楚，但是storager链接tracker时如果改成外网的ip就没问题。storager.conf tracker_server配置如下：
# tracker_server can ocur more than once, and tracker_server format is
#  "host:port", host can be hostname or ip address
tracker_server=域名:端口(外网地址)

**Comment by xiafish201** [comment]
这个问题怎么解决呢，有没有知道

**Comment by liu-yfeng** [comment]
这个问题解决了吗，最近我也遇到这个问题了

**Comment by shangmin1990** [comment]
解决方案:
storager.conf tracker_server配置如下：
tracker_server=域名:端口(外网地址)

**Comment by shangmin1990** [comment]
@liu-yfeng 
解决方案:
storager.conf tracker_server配置如下：
tracker_server=域名:端口(外网地址)

**Comment by lb-never** [comment]
不行吧？
用java-client操作的时候，先从tracker获取storage的ip和端口以及group，但是tracker获取storage的ip是storage自动去注册的，所以tracker获取到的storage的ip是容器内的
所以，是不是去看源码storage怎么注册到tracker的

**Comment by jinghuaz** [comment]
@lb-never  any update? 遇到一样的问题 docker ip

**Comment by jiatongwu** [comment]
storage配置成tracker外网ip后
storage端口启动不起来？

**Comment by cxydevelop** [comment]
情况一 : fastdfs部署在一个腾讯云上面 , 再storage中配置tracker的地址时,如果用外网ip, fastdfs启动不了 , tracker一直在选举 , 如果用内网地址就是ifconfig可以看到的那个ip , fastdfs时可以启动的,选举成功,也可以client上传个文件上去.然后我就本地代码想连上服务器,发现socket连接超时 , 估计是本地代码获取到的storage是内网地址导致连不上了 , 至今还不知道怎么解决.....
情况二 :  fastdfs部署在一个内网服务器上 , 使用docker , 基本流程一样,最后使用代码去上传文件时 , 获取到的storage是docker 容器里面的内网地址 , 导致还是不能使用
真的没想到使用fastdfs这么坎坷 , 救救孩子吧

**Comment by thisisrui** [comment]
方案1：参考 CodeManLH 的方案 [增加代理](https://github.com/happyfish100/fastdfs/issues/249#issuecomment-436564121)

方案2：参考 thisisrui 的方案 [增加 iptables nat 转发](https://github.com/happyfish100/fastdfs/issues/491#issuecomment-822945303)
