### ISSUE TITLE
关于6.06的双ip新特性，docker中应该如何配置以返回正确的storage ip？

### ISSUE THREAD

**Issue by xiaoxiongmao666** [happyfish100/fastdfs#439]
双ip有人仔细讲解一下吗，试了几下，就把storage1从容器虚拟网关172.17.0.1变到了容器虚拟ip172.17.0.2，对于docker外的客户端192.168.1.116还是访问不到。storage.conf的双ip和storage_ids.conf的双ip各自的用处是什么？

**Comment by xiaoxiongmao666** [comment]
1.给容器分配终端
2.vim /etc/fdfs/tracker.conf
3.找到use storage_ids的设置从false改为true
保存退出
4.vim /etc/fdfs/storage_ids.conf
5.添加100001   group1  172.17.0.1,192.168.1.25
保存退出
注意：192.168.1.25是宿主机ip，就是环境变量FASTDFS_IPADDR的值。只要是docker默认设置，内网ip都是172.17.0.1。
6.重启容器

其他解决方式：
1.创建容器时使用参数，从桥连改为host映射--net=host
2.使用k8s的服务发现
3.使用k8s的网络插件

备注：对于wsl2此方法无效，host也无效，只有使用k8s，没有继续尝试

**Comment by zk-shitou** [comment]
我遇到了同样的问题，在centos7.8环境下client连接tracker 容器返回的storage注册信息(ip)是正确的，但是在windows10 (home 1909)环境安装docker desktop(2.4.0.0 stable)，在同一个container 中安装了tracker 和 storage，遇到如下情况
![image](https://user-images.githubusercontent.com/48871656/100595331-bd786780-3335-11eb-986b-78ae6a79786f.png)
，有个帖子描述的比较清楚[docker安装fastdfs碰到storage的IP地址映射宿主地址问题](https://www.cnblogs.com/zzsdream/p/11199374.html)，该贴宿主机是linux环境使用了iptable解决了问题
我尝试了配置双ip，注册的仍然是docker0的ip，问题没有解决
![image](https://user-images.githubusercontent.com/48871656/100596311-f95ffc80-3336-11eb-8c1b-852fb02d14c0.png)
看了下双ip的介绍[FastDFS支持双IP](https://weibo.com/1401167985/I9ddWfGhT?type=comment)中写道
>  FastDFS支持双IP后，连接规则如下：
>   1. storage 连接storage server，优先尝试连接内网IP，失败了再尝试连接外网IP。（连接顺序可配置）
>   2. client向tracker server获取storage server IP，tracker server采用规则如下：
 >      外网过来的请求，返回外网IP；
 >      内网过来的请求，返回内网IP。

可能不能解决windows环境下client获取到storage信息错误。
现在依然在想办法处理，希望有遇到相同情况的人可以给个解决方案
