### ISSUE TITLE
store_lookup设置为轮询，上传之后马上下载和删除找不到文件，第二次才能成功

### ISSUE THREAD

**Issue by BryanChanCQ** [happyfish100/fastdfs#442]
我配置了两个group
tracker.conf文件中参数
store_lookup=0
下载及删除第一次找不到文件，点击下载及删除第二次请求才能成功
我想到的应该是storageserver以轮询的方式请求文件地址，所以才导致这个情况发生。
如果将store_lookup=2，以最大的存储空间上传。那么就完全正常，下载和删除都不会出现问题。
那么问题来了，如果以store_lookup=2的方式上传文件。group1空间满了，文件系统会往group2上面传文件。如果我想下载存储到group1的文件，那么就下载不到了，因为这个时候storageserver永远指向group2了（这个时候group2是空间最大的存储节点）。
请求是我配置哪里没有搞对吗？

**Comment by WhitePi** [comment]
![image](https://user-images.githubusercontent.com/26297347/91286113-9e12f100-e7c0-11ea-8729-ed01cf3557c6.png)
![image](https://user-images.githubusercontent.com/26297347/91286136-a79c5900-e7c0-11ea-8d0e-821f1fa3481d.png)
我们之前也碰到过，获取storage client的时候，把storageServer值为空就正常了

**Comment by BryanChanCQ** [comment]
> ![image](https://user-images.githubusercontent.com/26297347/91286113-9e12f100-e7c0-11ea-8729-ed01cf3557c6.png)
> ![image](https://user-images.githubusercontent.com/26297347/91286136-a79c5900-e7c0-11ea-8d0e-821f1fa3481d.png)
> 我们之前也碰到过，获取storage client的时候，把storageServer值为空就正常了

感谢小白的回复。
我的解决方案是，每次重新用groupName去获取StorageServer，确保获取到正确的存储节点服务。这个方法在引用包的源代码中可以找到。
<img width="694" alt="屏幕快照 2020-08-27 08 58 09" src="https://user-images.githubusercontent.com/49968907/91371474-a7916d00-e843-11ea-9fee-a5efd8ab9cbc.png">
