### ISSUE TITLE
银河麒麟 飞腾版 ARM 架构上编译问题

### ISSUE THREAD

**Issue by lovlyhao** [happyfish100/fastdfs#474]
fastdfs-5.05/make.sh 运行报如下错误

`linux_stack_trace.o ../common/linux_stack_trace.c -I../common -I/usr/include/fastcommon ../common/linux_stack_trace.c: 在函数‘signal_stack_trace_print’中: ../common/linux_stack_trace.c:79:17: 错误：‘NGREG’未声明(在此函数内第一次使用) for(i = 0; i < NGREG; i++) ^~~~~ ../common/linux_stack_trace.c:79:17: 附注：每个未声明的标识符在其出现的函数内只报告一次 ../common/linux_stack_trace.c:82:29: 错误：‘mcontext_t {或称 struct <匿名>}’ has no member named ‘gregs’; did you mean ‘regs’? i, ucontext->uc_mcontext.gregs[i]); ^~~~~ regs ../common/linux_stack_trace.c:149:2: 错误：‘sz’未声明(在此函数内第一次使用) sz = backtrace(bt, 20); ^~ ../common/linux_stack_trace.c:149:7: 警告：隐式声明函数‘backtrace’ [-Wimplicit-function-declaration] sz = backtrace(bt, 20); ^~~~~~~~~ ../common/linux_stack_trace.c:149:17: 错误：‘bt’ undeclared (first use in this function); did you mean ‘bp’? sz = backtrace(bt, 20); ^~ bp ../common/linux_stack_trace.c:150:2: 错误：‘strings’ undeclared (first use in this function); did you mean ‘sprintf’? strings = backtrace_symbols(bt, sz); ^~~~~~~ sprintf ../common/linux_stack_trace.c:150:12: 警告：隐式声明函数‘backtrace_symbols’ [-Wimplicit-function-declaration] strings = backtrace_symbols(bt, sz); ^~~~~~~~~~~~~~~~~ ../common/linux_stack_trace.c:67:7: 警告：未使用的变量‘buff’ [-Wunused-variable] char buff[256]; ^~~~ ../common/linux_stack_trace.c:66:7: 警告：未使用的变量‘cmd’ [-Wunused-variable] char cmd[256]; ^~~ ../common/linux_stack_trace.c:65:8: 警告：未使用的变量‘ip’ [-Wunused-variable] void *ip = NULL; ^~ ../common/linux_stack_trace.c:64:9: 警告：未使用的变量‘bp’ [-Wunused-variable] void **bp = NULL; ^~ ../common/linux_stack_trace.c:63:10: 警告：未使用的变量‘dlinfo’ [-Wunused-variable] Dl_info dlinfo; ^~~~~~ ../common/linux_stack_trace.c:61:9: 警告：未使用的变量‘f’ [-Wunused-variable] int i, f = 0; ^ make: *** [Makefile:25：../common/linux_stack_trace.o] 错误 1 cc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O -DDEBUG_FLAG -DOS_LINUX -DIOEVENT_USE_EPOLL -c -o tracker_client_thread.o tracker_client_thread.c -I. -Itrunk_mgr -I../common -I../tracker -I../client -Ifdht_client -I/usr/include/fastcommon`

**Comment by liyuanzhuafan** [comment]
我也是同样的问题，实测使用5.11版本可以正常安装，启动的时候需要修改tracker.conf：thread_stack_size = 1024KB
