### ISSUE TITLE
fastdfs6.0.6，libfastcommon1.0.45基于源码包的spec文件构建rpm包出错

### ISSUE THREAD

**Issue by sunyuanabcd** [happyfish100/fastdfs#480]
1、在libfastcommon/src/sockopt.h文件函数socketCreateExAuto是4个入参（428行），但fastdfs/storage/storage_sync_func.c（86行）调用时传入5个参数，多一个g_fdfs_connect_timeout，经查询此参数在后续未使用，可以去除。
2、文件 fastdfs.spec（128行）追加 /usr/bin/fdfs_regenerate_filename ，否则编译报错

**Comment by happyfish100** [comment]
感谢反馈。
第一个问题master之前已经修复。
第二个问题已修复，你可以使用 master或 tag： V6.07

**Comment by sunyuanabcd** [comment]
你好，对于CPU是MIPS架构的rpm文件制作，这方面有什么差异？

**Comment by sunyuanabcd** [comment]
你好，
       启动的时候 dmesg 的时候报 fdfsclient 的库文件找不到，但实际在相应的目录下都有此文件。把 nginx 的 core 文件放出来如下，请问这个大概是怎么回事？谢谢








--
江苏省港口集团信息科技有限公司
姓名：孙源
电话：13776418313
地址：南京市鼓楼区中山北路540号下关大厦


发件人：YuQing ***@***.***>
发送日期：2020-12-31 11:20:12
收件人：happyfish100/fastdfs ***@***.***>
抄送人：sunyuanabcd ***@***.***>,Author ***@***.***>
主题：Re: [happyfish100/fastdfs] fastdfs6.0.6，libfastcommon1.0.45基于源码包的spec文件构建rpm包出错 (#480)

感谢反馈。
 第一个问题master之前已经修复。
 第二个问题已修复，你可以使用 master或 tag： V6.07
