### ISSUE TITLE
安装6.0.6版本编译失败

### ISSUE THREAD

**Issue by gls3** [happyfish100/fastdfs#482]
libfastcommon-1.0.43安装成功，安装FastDFS-6.0.6版本编译失败，提示信息如下：

fdfs_monitor.c: In function ‘main’:
fdfs_monitor.c:124:9: warning: implicit declaration of function ‘conn_pool_parse_server_info’ [-Wimplicit-function-declaration]
         if ((result=conn_pool_parse_server_info(tracker_server, &conn,
         ^
fdfs_monitor.c: In function ‘list_storages’:
fdfs_monitor.c:299:3: warning: implicit declaration of function ‘long_to_comma_str’ [-Wimplicit-function-declaration]
   long_to_comma_str(pGroupStat->total_mb, szDiskTotalSpace),
   ^
fdfs_monitor.c:310:2: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘int’ [-Wformat=]
  );
  ^
fdfs_monitor.c:310:2: warning: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Wformat=]
fdfs_monitor.c:310:2: warning: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Wformat=]
fdfs_monitor.c:549:4: warning: format ‘%s’ expects argument of type ‘char *’, but argument 11 has type ‘int’ [-Wformat=]
    szSyncedDelaySeconds);
    ^
fdfs_monitor.c:549:4: warning: format ‘%s’ expects argument of type ‘char *’, but argument 12 has type ‘int’ [-Wformat=]
/tmp/cc6BFOy4.o: In function `list_storages':
/opt/fastdfs-6.06/client/fdfs_monitor.c:286: undefined reference to `long_to_comma_str'
/opt/fastdfs-6.06/client/fdfs_monitor.c:286: undefined reference to `long_to_comma_str'
/opt/fastdfs-6.06/client/fdfs_monitor.c:286: undefined reference to `long_to_comma_str'
/opt/fastdfs-6.06/client/fdfs_monitor.c:417: undefined reference to `long_to_comma_str'
/opt/fastdfs-6.06/client/fdfs_monitor.c:417: undefined reference to `long_to_comma_str'
../tracker/tracker_proto.o: In function `tracker_make_connection_ex':
/opt/fastdfs-6.06/tracker/tracker_proto.c:529: undefined reference to `conn_pool_connect_server'
../tracker/fdfs_shared_func.o: In function `fdfs_server_contain':
/opt/fastdfs-6.06/tracker/fdfs_shared_func.c:30: undefined reference to `FC_CONNECTION_SERVER_EQUAL'
/opt/fastdfs-6.06/tracker/fdfs_shared_func.c:35: undefined reference to `FC_CONNECTION_SERVER_EQUAL'
/opt/fastdfs-6.06/tracker/fdfs_shared_func.c:37: undefined reference to `FC_CONNECTION_SERVER_EQUAL'
/opt/fastdfs-6.06/tracker/fdfs_shared_func.c:44: undefined reference to `FC_CONNECTION_SERVER_EQUAL'
../tracker/fdfs_shared_func.o: In function `fdfs_set_server_info_index':
/opt/fastdfs-6.06/tracker/fdfs_shared_func.c:755: undefined reference to `FC_CONNECTION_SERVER_EQUAL'
../tracker/fdfs_shared_func.o: In function `fdfs_set_server_info':
/opt/fastdfs-6.06/tracker/fdfs_shared_func.c:769: undefined reference to `conn_pool_set_server_info'
../tracker/fdfs_shared_func.o: In function `fdfs_set_server_info_ex':
/opt/fastdfs-6.06/tracker/fdfs_shared_func.c:781: undefined reference to `conn_pool_set_server_info'
collect2: error: ld returned 1 exit status
make: *** [fdfs_monitor] Error 1

**Comment by happyfish100** [comment]
你直接使用最新版本V6.07吧。

**Comment by gls3** [comment]
> 你直接使用最新版本V6.07吧。

使用最新的libfastcommon版本和最新版本V6.07，还是无法安装：

/tmp/cc5kmS2Z.o: In function `list_storages':
/opt/fastdfs/client/fdfs_monitor.c:286: undefined reference to `long_to_comma_str'
/opt/fastdfs/client/fdfs_monitor.c:286: undefined reference to `long_to_comma_str'
/opt/fastdfs/client/fdfs_monitor.c:286: undefined reference to `long_to_comma_str'
/opt/fastdfs/client/fdfs_monitor.c:417: undefined reference to `long_to_comma_str'
/opt/fastdfs/client/fdfs_monitor.c:417: undefined reference to `long_to_comma_str'
../common/fdfs_http_shared.o: In function `fdfs_http_params_load':
/opt/fastdfs/client/../common/fdfs_http_shared.c:116: undefined reference to `iniGetBoolValue'
/opt/fastdfs/client/../common/fdfs_http_shared.c:123: undefined reference to `iniGetBoolValue'
/opt/fastdfs/client/../common/fdfs_http_shared.c:127: undefined reference to `iniGetBoolValue'
/opt/fastdfs/client/../common/fdfs_http_shared.c:131: undefined reference to `iniGetIntValue'
/opt/fastdfs/client/../common/fdfs_http_shared.c:141: undefined reference to `iniGetBoolValue'
/opt/fastdfs/client/../common/fdfs_http_shared.c:147: undefined reference to `iniGetStrValue'
/opt/fastdfs/client/../common/fdfs_http_shared.c:204: undefined reference to `iniGetStrValue'
/opt/fastdfs/client/../common/fdfs_http_shared.c:232: undefined reference to `iniGetIntValue'
/opt/fastdfs/client/../common/fdfs_http_shared.c:243: undefined reference to `iniGetStrValue'
/opt/fastdfs/client/../common/fdfs_http_shared.c:256: undefined reference to `iniGetStrValue'
../tracker/tracker_proto.o: In function `tracker_make_connection_ex':
/opt/fastdfs/tracker/tracker_proto.c:529: undefined reference to `conn_pool_connect_server'
../tracker/fdfs_shared_func.o: In function `fdfs_server_contain':
/opt/fastdfs/tracker/fdfs_shared_func.c:30: undefined reference to `FC_CONNECTION_SERVER_EQUAL'
/opt/fastdfs/tracker/fdfs_shared_func.c:35: undefined reference to `FC_CONNECTION_SERVER_EQUAL'
/opt/fastdfs/tracker/fdfs_shared_func.c:37: undefined reference to `FC_CONNECTION_SERVER_EQUAL'
/opt/fastdfs/tracker/fdfs_shared_func.c:44: undefined reference to `FC_CONNECTION_SERVER_EQUAL'
../tracker/fdfs_shared_func.o: In function `fdfs_parse_storage_reserved_space':
/opt/fastdfs/tracker/fdfs_shared_func.c:204: undefined reference to `iniGetStrValue'
../tracker/fdfs_shared_func.o: In function `fdfs_connection_pool_init':
/opt/fastdfs/tracker/fdfs_shared_func.c:397: undefined reference to `iniGetBoolValue'
/opt/fastdfs/tracker/fdfs_shared_func.c:404: undefined reference to `iniGetIntValue'
/opt/fastdfs/tracker/fdfs_shared_func.c:416: undefined reference to `conn_pool_init'
../tracker/fdfs_shared_func.o: In function `fdfs_set_server_info_index':
/opt/fastdfs/tracker/fdfs_shared_func.c:755: undefined reference to `FC_CONNECTION_SERVER_EQUAL'
../tracker/fdfs_shared_func.o: In function `fdfs_set_server_info':
/opt/fastdfs/tracker/fdfs_shared_func.c:769: undefined reference to `conn_pool_set_server_info'
../tracker/fdfs_shared_func.o: In function `fdfs_set_server_info_ex':
/opt/fastdfs/tracker/fdfs_shared_func.c:781: undefined reference to `conn_pool_set_server_info'
../tracker/fdfs_server_id_func.o: In function `fdfs_load_storage_ids_from_file':
/opt/fastdfs/tracker/fdfs_server_id_func.c:768: undefined reference to `iniGetStrValue'
../storage/trunk_mgr/trunk_shared.o: In function `storage_load_paths_from_conf_file_ex':
/opt/fastdfs/client/../storage/trunk_mgr/trunk_shared.c:58: undefined reference to `iniGetIntValue'
/opt/fastdfs/client/../storage/trunk_mgr/trunk_shared.c:82: undefined reference to `iniGetStrValue'
/opt/fastdfs/client/../storage/trunk_mgr/trunk_shared.c:116: undefined reference to `iniGetStrValue'
../storage/trunk_mgr/trunk_shared.o: In function `storage_load_paths_from_conf_file':
/opt/fastdfs/client/../storage/trunk_mgr/trunk_shared.c:180: undefined reference to `iniGetStrValue'
client_func.o: In function `fdfs_get_params_from_tracker':
/opt/fastdfs/client/client_func.c:249: undefined reference to `iniGetBoolValue'
client_func.o: In function `fdfs_client_do_init_ex':
/opt/fastdfs/client/client_func.c:270: undefined reference to `iniGetStrValue'
/opt/fastdfs/client/client_func.c:296: undefined reference to `iniGetIntValue'
/opt/fastdfs/client/client_func.c:303: undefined reference to `iniGetIntValue'
/opt/fastdfs/client/client_func.c:316: undefined reference to `iniGetBoolValue'
/opt/fastdfs/client/client_func.c:323: undefined reference to `iniGetStrValue'
/opt/fastdfs/client/client_func.c:338: undefined reference to `iniGetIntValue'
/opt/fastdfs/client/client_func.c:351: undefined reference to `iniGetBoolValue'
/opt/fastdfs/client/client_func.c:360: undefined reference to `iniGetBoolValue'
collect2: error: ld returned 1 exit status
make: *** [fdfs_monitor] Error 1
mkdir -p /usr/bin
mkdir -p /etc/fdfs
cp -f fdfs_trackerd /usr/bin
cp: cannot stat ‘fdfs_trackerd’: No such file or directory
make: *** [install] Error 1
mkdir -p /usr/bin
mkdir -p /etc/fdfs
cp -f fdfs_storaged  /usr/bin
cp: cannot stat ‘fdfs_storaged’: No such file or directory
make: *** [install] Error 1
mkdir -p /usr/bin
mkdir -p /etc/fdfs
mkdir -p /usr/lib64
mkdir -p /usr/lib
cp -f fdfs_monitor fdfs_test fdfs_test1 fdfs_crc32 fdfs_upload_file fdfs_download_file fdfs_delete_file fdfs_file_info fdfs_appender_test fdfs_appender_test1 fdfs_append_file fdfs_upload_appender fdfs_regenerate_filename /usr/bin
cp: cannot stat ‘fdfs_monitor’: No such file or directory
cp: cannot stat ‘fdfs_test’: No such file or directory
cp: cannot stat ‘fdfs_test1’: No such file or directory
cp: cannot stat ‘fdfs_crc32’: No such file or directory
cp: cannot stat ‘fdfs_upload_file’: No such file or directory
cp: cannot stat ‘fdfs_download_file’: No such file or directory
cp: cannot stat ‘fdfs_delete_file’: No such file or directory
cp: cannot stat ‘fdfs_file_info’: No such file or directory
cp: cannot stat ‘fdfs_appender_test’: No such file or directory
cp: cannot stat ‘fdfs_appender_test1’: No such file or directory
cp: cannot stat ‘fdfs_append_file’: No such file or directory
cp: cannot stat ‘fdfs_upload_appender’: No such file or directory
cp: cannot stat ‘fdfs_regenerate_filename’: No such file or directory
make: *** [install] Error 1

**Comment by happyfish100** [comment]
编译前需要执行  ./make.sh clean
你可以参照源码目录下的 INSTALL文档。

**Comment by gls3** [comment]
在已经安装过旧版的服务器上无法安装，更换新的服务器即可安装成功
