### ISSUE TITLE
storager中出现大量文件大小为0的文件无法访问。

### ISSUE THREAD

**Issue by Singa-dev** [happyfish100/fastdfs#485]
今天发现在storager中出现了很多文件大小为0的文件，并且不能访问。
从客户端访问也不行。
还请大神指点一下，多谢了。

**Comment by happyfish100** [comment]
请问你用的什么版本呢？
如果使用 V5.12 或者 V6.07，应该不存在这个问题的。
建议使用最新的V6.07。

**Comment by Singa-dev** [comment]
而且名字多以wKgAf2AIW96AXGmVAAAAAAAAAAA760.jpg，wKgAf2AIW1OAWOnjAAAAAAAAAAA422.jpg这样为主，其共同特点是里面都有一连串的AAAAAAAAA。

**Comment by Singa-dev** [comment]
另外，我现在使用的就是最新的版本：FastDFS server v6.07

**Comment by happyfish100** [comment]
这个应该是你们应用程序上传了字节数为0的图片，开发工程师需要排查。

**Comment by Singa-dev** [comment]
哦，感谢感谢。
