### ISSUE TITLE
请问storaged的最大连接数是256，即使配置再高也不生效吗。我将tracker和storage的max_connections设置为500后，连接数还是维持在240左右，感觉没有生效，报错依然存在

### ISSUE THREAD

**Issue by zjun1001** [happyfish100/fastdfs#489]
tracker_nio.c, line: 140, malloc task buff failed, you should increase the parameter: max_connections

**Comment by happyfish100** [comment]
这个参数可以配置得更大一些，至少配置1024吧。
另外，可能是应用（调用方）程序有连接泄露问题。

**Comment by zjun1001** [comment]
后来排查确是调用方问题，客户端用的是C++。上传图片失败后，会有三次重试机会，这块逻辑它没有关闭之前的连接，而是直接建立了新连接，导致连接很快被占满。
