### ISSUE TITLE
V6.07手动启动命令后会卡住，需要配置什么？

### ISSUE THREAD

**Issue by calibura** [happyfish100/fastdfs#494]
## info
v6.07

# uname -a
Linux centos7.linuxvmimages.local 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

service fdfs_trackerd start
service fdfs_storaged start
---
启动后会卡在
例如 
# service fdfs_storaged start
Redirecting to /bin/systemctl start fdfs_storaged.service

只能^C

## 查询
# netstat -unltp|grep fdfs
tcp        0      0 0.0.0.0:22122           0.0.0.0:*               LISTEN      2378/fdfs_trackerd
tcp        0      0 0.0.0.0:23000           0.0.0.0:*               LISTEN      2599/fdfs_storaged

## 通讯 ACTIVE

新手表示很疑惑

这是还需要配置什么吗？为什么手动启动会卡住

**Comment by forecloud** [comment]
systemctl status fdfs_storaged.service
通过以上命令可以看到报错信息
Can't open PID file /opt/fastcfs/data/fdfs_storaged.pid (yet?) after start: No such file or directory
但是暂时不知道需要改什么地方去修改pid的位置,不过服务是起来了
只是/etc/init.d/fdfs_storaged start这个命令就总是会卡住....

**Comment by forecloud** [comment]
我的解决了
find / -name fdfs_storaged.service
里面有这个pid配置
find / -name fdfs_storaged.pid 
改成实际路径就可以了

**Comment by calibura** [comment]
感谢
