### ISSUE TITLE
Distributed file system?  Object storage?

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [happyfish100/fastdfs#500]
Hello, I'm currently evaluating this solution and am confused about which category of the storage system is FastDFS in.  The DFS suffix stands for distributed file system but it doesn't provide a typical directory tree interface like NFS/HDFS, and the uploaded files' encoded path looks like an object storage system(Like MinIO/Amazon S3).

Am I misinterpreting the concept or does FastDFS is really an object storage solution?

Thanks in advance!

**Comment by happyfish100** [comment]
FastDFS is a distributed file system for object storage.

**Comment by Lin-Buo-Ren** [comment]
Thanks for the clarification.
