### ISSUE TITLE
libfastcommon编译失败

### ISSUE THREAD

**Issue by issyu-summer** [happyfish100/fastdfs#508]
![image](https://user-images.githubusercontent.com/61642788/123802698-28b30800-d91e-11eb-9de2-f36462ac4ea4.png)

**Comment by happyfish100** [comment]
请问使用的是 master分支吗？另外麻烦告知一下操作系统版本号

**Comment by happyfish100** [comment]
Ubuntu下编译的确报错，已修复。
感谢反馈！
