### ISSUE TITLE
请教大佬 fastdfs-nginx-module模块问题

### ISSUE THREAD

**Issue by fengaixue** [happyfish100/fastdfs#517]
使用nginx模块，除了可以提供直接HTTP访问功能外，还有其他作用吗？

**Comment by fengaixue** [comment]
不适用这个模块会怎么样？

**Comment by YogurtOlderMan** [comment]
这个模块有以下作用：
1、 页面访问
2、 快速检索文件

我们之前遇到过一个问题，就是多storage时，由于storage之间同步需要时间，这时请求很有可能会落到没有相关文件的storage上，系统就会报404，表示没又找到此文件，但实际上是因为storage之间没有同步完成造成的
