### ISSUE TITLE
合并开启后会不会造成大文件内部的碎片空洞

### ISSUE THREAD

**Issue by perfgao** [happyfish100/fastdfs#519]
Hi，
我这边有个疑问需要请教下，如果fastdfs存储中，开启了小文件合并功能，同时，该系统中小文件会有相当数量的更新、增加、删除，这种情况下，是否可以开启合并功能？
文件改写和删除，会不会造成大文件内部的碎片空洞？

**Comment by jerrypicasso** [comment]
> 
> 
> Hi， 我这边有个疑问需要请教下，如果fastdfs存储中，开启了小文件合并功能，同时，该系统中小文件会有相当数量的更新、增加、删除，这种情况下，是否可以开启合并功能？ 文件改写和删除，会不会造成大文件内部的碎片空洞？

我也有相同的疑问，求解

**Comment by happyfish100** [comment]
已删除空间会回收利用的。
