### ISSUE TITLE
nginx会不停的启动和管理线程导致访问nginx失败，有大佬知道这个是什么情况吗？

### ISSUE THREAD

**Issue by zj19950922** [happyfish100/fastdfs#522]
![1629885240(1)](https://user-images.githubusercontent.com/48822075/130769726-e6cfd11b-9e35-4a58-a7a3-260d0b8e87a2.png)
![1629885265(1)](https://user-images.githubusercontent.com/48822075/130769771-bbaa390e-a7d5-4485-9494-65128a479860.png)

**Comment by happyfish100** [comment]
需要重新编译和安装 nginx
