### ISSUE TITLE
关于storage的ip问题

### ISSUE THREAD

**Issue by cksspk** [happyfish100/fastdfs#530]
是这样的一个场景，有一台内网centos7部署了docker版本tracker和storage
网络环境通过frp进行内网穿透。frp服务端是阿里云，客户端是centos7。
我可以通过阿里云22122转口转到内网tracker的22122端口，并在tracker容器修改了/etc/fdfs/client.conf配置。设置tracker_server= （公网ip：22122）
我在java客户端的时候通过使用 公网ip：22122 可以连上tracker，但是返回storage的是192.168.2.190这个内网地址。
这个问题有什么办法可以解决吗？

**Comment by happyfish100** [comment]
可以试试最新的 V6版本，比如 V6.09

**Comment by rea-leaf** [comment]
这个问题 我也遇到了，用的是最新的版本6.12.2 还是有这个问题的

**Comment by happyfish100** [comment]
要使用双 IP 特性，storage server配置双 IP 即可
