### ISSUE TITLE
libfastcommon 编译 出现 nm: '/usr/lib/libc_r.so': No such file #41

### ISSUE THREAD

**Issue by HOSystemH** [happyfish100/fastdfs#531]
直接通过 git clone https://github.com/happyfish100/libfastcommon.git --depth 1
执行make.sh出现错误
./make.sh: line 172: warning: here-document at line 2 delimited by end-of-file (wanted `EOF')
./make.sh: line 2: ./a.out: No such file or directory
./make.sh: line 2: +: command not found
nm: '/usr/lib/libc_r.so': No such file

**Comment by happyfish100** [comment]
请问使用的什么操作系统和版本呢？

**Comment by wangrongwang** [comment]
楼主解决了吗，求指教

**Comment by happyfish100** [comment]
貌似楼主的编译环境异常。
另外，libfastcommon用的什么版本呢？

**Comment by hakurui** [comment]
> 楼主解决了吗，求指教

解决了，你在本地 git clone 代码，然后再上传上去就可以了。不知道为什么直接拉取不行

**Comment by hakurui** [comment]
> 

并不是，直接git clone 再linux好像不行，我试了3-4台虚拟机；换电脑也是这个问题。所以直接git到windows然后在上传到linux上就行了
