### ISSUE TITLE
Bug Report: storage_sync.c函数storage_binlog_write_ex错误处理问题

### ISSUE THREAD

**Issue by giantpoplar** [happyfish100/fastdfs#532]
在storage_binlog_write_ex中：

> 
......
if ((result=pthread_mutex_lock(&sync_thread_lock)) != 0)
	{
		logError("file: "__FILE__", line: %d, " \
			"call pthread_mutex_lock fail, " \
			"errno: %d, error info: %s", \
			__LINE__, result, STRERROR(result));
	}
......

这里lock出错后，依然继续往下处理，这个是有点问题的吧？我们在做高并发删除的时候，fastdfs生成了下面的binlog，有1行文件名为空，然后sync线程scan到这一行也进行不下去了

> 
......
1632325133 D M05/7D/61/CgI4e1x2DRaAW2p9AAABkZO6WB0987.xml
1632325133 D M04/4D/09/CgI4e1u02YSAI9zfAAABkbzo4K8546.xml
1632325133 D
1632325133 D M03/59/C6/CgI4e1u1kIaAUfFWAAAfZyKjO1M782.xml
1632325133 D M0A/F8/65/CgI4el2vLk6AcgNDAAAWLPouIAM000.xml
......

**Comment by happyfish100** [comment]
删除掉有问题的binlog内容即可

**Comment by happyfish100** [comment]
很奇怪为啥会出现不完整的binlog记录。麻烦告知使用的 FastDFS版本
