### ISSUE TITLE
最新版本v6.0.7 编译时报错

### ISSUE THREAD

**Issue by EircYangQiXin** [happyfish100/fastdfs#544]
已经安装了libfastcommon 也是最新版本的，编译也没有问题
但是安装fastdfs的时候执行./make.sh 报错
这是啥原因啊？
![image](https://user-images.githubusercontent.com/37945692/147073642-b0cdff26-2515-463c-90a6-0781ef75ab3d.png)
![1640166902(1)](https://user-images.githubusercontent.com/37945692/147073633-8f52097c-f207-43fa-a47d-c7cf4c72e12d.jpg)

**Comment by EircYangQiXin** [comment]
我的linux 版本是centos 7.9

**Comment by SakuraLQY** [comment]
同问

**Comment by happyfish100** [comment]
安装最新的 6.09试试，用 master分支即可。
