### ISSUE TITLE
获取文件所在storage 的 Ip出错

### ISSUE THREAD

**Issue by Mjzll** [happyfish100/fastdfs#548]
-  文件上传成功后，使用Fastdfs-client获取其可下载的storageIp，集群中有两台fastdfs-traker返回的storage ip 有误
![image](https://user-images.githubusercontent.com/50262361/149506525-0f95c486-87cc-4dfd-bb3f-1b03886e65b0.png)

**Comment by happyfish100** [comment]
使用 FastDFS最新版本已经解决这个问题，请升级到最新版本V6.07
