### ISSUE TITLE
关于docker容器化编译、部署咨询一些建议

### ISSUE THREAD

**Issue by qifengzhang007** [happyfish100/fastdfs#549]
###  一些自述
- 1.本人计划将 `nginx `、`tracker`、`storage  `通过 `docker `容器方式分别部署在不同服务器。`nginx `始终作为前置代理服务器。
- 2.目前基于 `alpine `编译 `nginx`（包括 `nginx-dfs` 模块）、`tracker、storage `编译全部通过（感谢作者最近更新解决了 `alpine `环境报错问题）

### 目前遇到的问题
- 1.编译 `nginx `时，有个文件：`fastdfs-nginx-module-1.22/src/common.c ` 依赖了以下头文件.
```code
#include "fastcommon/logger.h"
#include "fastcommon/shared_func.h"
#include "fastcommon/sockopt.h"
#include "fastcommon/http_func.h"
#include "fastcommon/local_ip_func.h"
#include "fastdfs/fdfs_define.h"
#include "fastdfs/fdfs_global.h"
#include "fastdfs/fdfs_http_shared.h"
#include "fastdfs/fdfs_client.h"
#include "fastdfs/fdfs_shared_func.h"
#include "fastdfs/trunk_shared.h"
#include "common.h"

```
以上依赖的头文中，依赖 `fastcommon `部分文件属于公共函数部分，无可厚非，
但是依赖 `fastdfs `相关的文件有些疑惑，这就意味着 `nginx `必须和 `fastdfs `服务放置在同一台机器(或者说容器编译时必须把`fastdfs `先编译了，尽管可以在 `nginx `容器不需要启动 `fastdfs `)，
请问 `nginx `依赖的 `fastfds `库不知道是否可以像 `libcommon `一样精简一下呢？将 `nginx `的编译和 `fastdfs `尽量分开、独立。

**Comment by happyfish100** [comment]
FastDFS为nginx提供的扩展依赖 FastDFS的client library，只需要编译和安装 FastDFS client library即可。

**Comment by qifengzhang007** [comment]
> FastDFS为nginx提供的扩展依赖 FastDFS的client library，只需要编译和安装 FastDFS client library即可。

fastdfs 的 client 部分编译，作者抽空独立出来，提供一个单独仓库可以吗？
目前这块的编译是被捆绑在了 fastdfs 主仓库了。
