### ISSUE TITLE
关于nginx-module的问题

### ISSUE THREAD

**Issue by javaoldwang** [happyfish100/fastdfs#550]
一次部署经历，在部署fastdfs-nginx-module的时候，最新的版本总提示：unknown directive "ngx_fastdfs_module"，请问下有没有同样问题的小伙伴。我的nginx是最新下载的1.19.9版本，centos中并没有事先启动过nginx。

**Comment by andylau004** [comment]
可能需要 编译nginx的时候；加上
--add-module=[fastdfs-nginx-module 路径]/src
