### ISSUE TITLE
systemd必须以固定格式结尾

### ISSUE THREAD

**Issue by jschunlei** [happyfish100/fastdfs#576]
留个脚印,感觉有人会遇到一样的问题.
fdfs_trackerd.service 代码中写死PIDFile必须以 /data/fdfs_trackerd.pid结尾,示例PIDFile=XXX路径/data/fdfs_trackerd.pid
文件tracker/fdfs_trackerd.c:
```
	snprintf(pidFilename, sizeof(pidFilename),
		"%s/data/fdfs_trackerd.pid", g_fdfs_base_path);
```

fdfs_storaged.service 代码中写死PIDFile必须以 /data/fdfs_storaged.pid结尾,示例PIDFile=XXX路径/data/fdfs_storaged.pid
文件storage/fdfs_storaged.c:
```
	snprintf(pidFilename, sizeof(pidFilename),
		"%s/data/fdfs_storaged.pid", g_fdfs_base_path);
```

**Comment by happyfish100** [comment]
感谢反馈，已整理到 wiki中。
