### ISSUE TITLE
有大量图片需要保存到dfs，我直接粘贴到了/data/00/00的目录下，但是无法访问

### ISSUE THREAD

**Issue by x136931283** [happyfish100/fastdfs#580]
我直接将大量图片 复制粘贴到/data/00/00、无法通过 http://127.0.0.1:8888/group1/M00/00/00/xxx.jpg 访问。怎么办？还需要做什么？难道要我用程序一张张上传才能正常访问吗

**Comment by happyfish100** [comment]
你这样的做法(需求），可以试试 FastCFS
