### ISSUE TITLE
不知道为什么启动不了

### ISSUE THREAD

**Issue by Steve-God** [happyfish100/fastdfs#582]
● fdfs_trackerd.service - FastDFS trackerd service
   Loaded: loaded (/usr/lib/systemd/system/fdfs_trackerd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since 一 2022-08-29 22:07:11 CST; 5s ago
  Process: 13407 ExecStart=/usr/bin/fdfs_trackerd /etc/fdfs/tracker.conf start (code=exited, status=22)

8月 29 22:07:11 localhost.localdomain systemd[1]: Starting FastDFS trackerd service...
8月 29 22:07:11 localhost.localdomain fdfs_trackerd[13407]: get pid from file: /home/data/fastdfs/tracker/data/fdfs_trackerd.pid fail, errno: 22, error info: Invalid argument
8月 29 22:07:11 localhost.localdomain fdfs_trackerd[13407]: FastDFS server v6.08
8月 29 22:07:11 localhost.localdomain fdfs_trackerd[13407]: Usage: /usr/bin/fdfs_trackerd <config_file> [start | stop | restart]
8月 29 22:07:11 localhost.localdomain systemd[1]: fdfs_trackerd.service: control process exited, code=exited status=22
8月 29 22:07:11 localhost.localdomain systemd[1]: Failed to start FastDFS trackerd service.
8月 29 22:07:11 localhost.localdomain systemd[1]: Unit fdfs_trackerd.service entered failed state.
8月 29 22:07:11 localhost.localdomain systemd[1]: fdfs_trackerd.service failed.

**Comment by happyfish100** [comment]
pid文件内容有误，可以删除pid文件后试试

**Comment by Steve-God** [comment]
> pid文件内容有误，可以删除pid文件后试试

搞好了 直接把service的pid删了
