### ISSUE TITLE
生产环境存在不稳定的tracker集群，执行/usr/local/bin/fdfs_monitor偶尔会导致tracker有Bad file descriptor报错

### ISSUE THREAD

**Issue by LinZhenLin** [happyfish100/fastdfs#583]
背景:
1) 某日，生产环境的某个tracker集群(副本数为2，版本为v5.0.5)，开始爆大量的Bad file descriptor报错，日志量非常大，一旦触发，能写满整个磁盘
具体日志如下所示：
tracker日志：
![图片](https://user-images.githubusercontent.com/28896934/187889374-d9b9421d-9d33-4b83-b938-e5cdfcfafc58.png)
linux var log日志
![图片](https://user-images.githubusercontent.com/28896934/187891189-75f4fd36-b7bc-4e50-a0f6-717f40889e03.png)
我这边也有对应的core.dump文件，如果需要，请反馈给我
2) 此时，此类报错是偶发的，在进行对storage server的tracker_server配置从旧集群直接改成新的tracker的过程，发现storage迁移重启后，只要触发
`/usr/local/bin/fdfs_monitor <config_file> [-h <tracker_server>] list ` 
ps：这里的命令tracker是旧的tracker集群，此时还关联着其他未迁移的storage_server
结果正常返回，但是等待一会，其tracker日志开始报错刷屏。
3) 迁移完成后，我个人对其场景模拟，但是结果一切正常，怀疑是对应的tracker集群存在着问题。

**Comment by happyfish100** [comment]
版本太旧了，建议升级到最新版本。
