### ISSUE TITLE
fastdfs进行配置文件时已经有tracker.conf了

### ISSUE THREAD

**Issue by SakuraLQY** [happyfish100/fastdfs#587]
cp /etc/fdfs/tracker.conf.sample /etc/fdfs/tracker.conf出现p: 无法获取"/etc/fdfs/tracker.conf.sample" 的文件状态(stat): 没有那个文件或目录；是新版本已经配置好了吗

**Comment by happyfish100** [comment]
是的。wiki文档已更新。
