### ISSUE TITLE
最新版本支持前台启动fastdfs了吗？

### ISSUE THREAD

**Issue by GeXin666** [happyfish100/fastdfs#589]
作者您好，我希望使用supervisor管理进程，希望能够在前台启动fastdfs，请问该怎么做？
类似的比如nginx，可以通过 /usr/local/nginx/sbin/nginx -g 'daemon off;' 指定前台启动。

**Comment by happyfish100** [comment]
最新的 v6.09 已经支持了，启动 fdfs_trackerd 或 fdfs_storaged，加上参数 -N 即可。

**Comment by GeXin666** [comment]
谢谢大佬的回复，马上更新，结合supervisor后会非常完美。
