### ISSUE TITLE
fastdfs编译时出现文件夹不存在的错误

### ISSUE THREAD

**Issue by isvttr** [happyfish100/fastdfs#590]
[root@192 fastdfs]# ./make.sh && ./make.sh install
gcc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O1 -DDEBUG_FLAG -c -o ../common/fdfs_global.o ../common/fdfs_global.c  -I../common -I/usr/local/include
In file included from ../common/fdfs_global.c:21:0:
../common/fdfs_global.h:15:26: 致命错误：sf/sf_global.h：没有那个文件或目录
 #include "sf/sf_global.h"
                          ^
编译中断。
make: *** [../common/fdfs_global.o] 错误 1
gcc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O1 -DDEBUG_FLAG -c -o ../common/fdfs_global.o ../common/fdfs_global.c  -I. -Itrunk_mgr -I../common -I../tracker -I../client -Ifdht_client -I/usr/include/fastcommon
In file included from ../common/fdfs_global.c:21:0:
../common/fdfs_global.h:15:26: 致命错误：sf/sf_global.h：没有那个文件或目录
 #include "sf/sf_global.h"
                          ^
编译中断。
make: *** [../common/fdfs_global.o] 错误 1
gcc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O1 -DDEBUG_FLAG -c -o ../common/fdfs_global.o ../common/fdfs_global.c  -I../common -I../tracker -I/usr/include/fastcommon
In file included from ../common/fdfs_global.c:21:0:
../common/fdfs_global.h:15:26: 致命错误：sf/sf_global.h：没有那个文件或目录
 #include "sf/sf_global.h"
                          ^
编译中断。
make: *** [../common/fdfs_global.o] 错误 1
mkdir -p /usr/bin
mkdir -p /etc/fdfs
cp -f fdfs_trackerd /usr/bin
cp: 无法获取"fdfs_trackerd" 的文件状态(stat): 没有那个文件或目录
make: *** [install] 错误 1
mkdir -p /usr/bin
mkdir -p /etc/fdfs
cp -f fdfs_storaged  /usr/bin
cp: 无法获取"fdfs_storaged" 的文件状态(stat): 没有那个文件或目录
make: *** [install] 错误 1
mkdir -p /usr/bin
mkdir -p /etc/fdfs
mkdir -p /usr/lib64
mkdir -p /usr/lib
cp -f fdfs_monitor fdfs_test fdfs_test1 fdfs_crc32 fdfs_upload_file fdfs_download_file fdfs_delete_file fdfs_file_info fdfs_appender_test fdfs_appender_test1 fdfs_append_file fdfs_upload_appender fdfs_regenerate_filename /usr/bin
cp: 无法获取"fdfs_monitor" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"fdfs_test" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"fdfs_test1" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"fdfs_crc32" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"fdfs_upload_file" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"fdfs_download_file" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"fdfs_delete_file" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"fdfs_file_info" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"fdfs_appender_test" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"fdfs_appender_test1" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"fdfs_append_file" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"fdfs_upload_appender" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"fdfs_regenerate_filename" 的文件状态(stat): 没有那个文件或目录
make: *** [install] 错误 1

**Comment by happyfish100** [comment]
需要编译和安装 libserverframe

**Comment by tokenwind** [comment]
> 需要编译和安装 libserverframe

wiki 没有那边安装说明没有更新，大佬记得更新下。
`git clone https://github.com/happyfish100/libserverframe.git`

**Comment by happyfish100** [comment]
wiki文档已补充，感谢反馈。
