### ISSUE TITLE
根据步骤安装和编译fastdfs之后，对配置文件操作出现异常

### ISSUE THREAD

**Issue by isvttr** [happyfish100/fastdfs#593]
[root@VM-12-2-centos fastdfs]# cp /etc/fdfs/tracker.conf.sample /etc/fdfs/tracker.conf
cp: cannot stat ‘/etc/fdfs/tracker.conf.sample’: No such file or directory

[root@VM-12-2-centos fastdfs]# cp /etc/fdfs/tracker.conf.sample /etc/fdfs/tracker.conf
cp: cannot stat ‘/etc/fdfs/tracker.conf.sample’: No such file or directory

[root@VM-12-2-centos fastdfs]# cp /etc/fdfs/storage.conf.sample /etc/fdfs/storage.conf
cp: cannot stat ‘/etc/fdfs/storage.conf.sample’: No such file or directory

**Comment by reatiny** [comment]
+1

**Comment by happyfish100** [comment]
已经没有 后缀名为sample的配置文件了，不再需要 cp这一步。

**Comment by happyfish100** [comment]
感谢反馈，wiki文档已更新。
