### ISSUE TITLE
关于文件命名问题

### ISSUE THREAD

**Issue by qinxh** [happyfish100/fastdfs#594]
1.能否根据自己传入的文件去命名，而不使用fastfds提供而命名功能
2.是否可以提供文件上传覆盖功能，比如在微服务场景下，可能存在同一个文件上传后，名称在多个服务中有冗余，这是如果业务需求需要替换下文件。如果fastfds能够支持传入文件名直接覆盖，那各个服务中就不用同步修改名称了

**Comment by happyfish100** [comment]
你这个需求可以试试通用文件系统 FastCFS
