### ISSUE TITLE
作者您好，我希望从V6.08升级到V6.09是否兼容？

### ISSUE THREAD

**Issue by GeXin666** [happyfish100/fastdfs#596]
目前线上版本是V6.08，希望升级到V6.09：
步骤1：暂停线上服务，删除二进制文件 rm -rf /usr/bin/fdfs*，保留配置文件和数据文件
步骤2：重新编译v6.09   ./make.sh && ./make.sh install 
步骤3：编译完以后重新启动器群。
目前依赖版本

请问作者：
1：V6.08升级到V6.09是否兼容？
2：上述升级步骤是否可行，还有没有漏项？
3：目前依赖工具 libfastcommon-1.0.57.tar.gz 和 fastdfs-nginx-module-1.22.tar.gz 需要升级吗？

非常感谢大佬！

**Comment by happyfish100** [comment]
完全兼容的，请放心升级程序
