### ISSUE TITLE
service fdfs_trackerd start 卡死

### ISSUE THREAD

**Issue by oxygengas** [happyfish100/fastdfs#599]
[root@node1 fdfs]#  service fdfs_trackerd start
Redirecting to /bin/systemctl start fdfs_trackerd.service
这里会一直等待。。。

**Comment by happyfish100** [comment]
用的什么版本呢？

**Comment by oxygengas** [comment]
您好，最新版fastdfs-6.09，除了卡一下强制退出。其它都正常，日志也没看出问题
服务器版本：centsos 7.5





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "happyfish100/fastdfs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月23日(星期三) 中午11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [happyfish100/fastdfs] service fdfs_trackerd start 卡死 (Issue #599)





 
用的什么版本呢？

**Comment by happyfish100** [comment]
配置文件中的base_path 你修改过吗？

**Comment by oxygengas** [comment]
修改过，权限都给了 参数在附件中，麻烦看看







549574553
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "happyfish100/fastdfs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月23日(星期三) 下午2:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [happyfish100/fastdfs] service fdfs_trackerd start 卡死 (Issue #599)





 
配置文件中的base_path 你修改过吗？

**Comment by oxygengas** [comment]
除了启动卡死，其它一切使用正常。Ctrl+C结束卡死的进程，ps查看都是正常启动。fdfs-client上传正常


549574553
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "happyfish100/fastdfs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月23日(星期三) 下午2:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [happyfish100/fastdfs] service fdfs_trackerd start 卡死 (Issue #599)





 
配置文件中的base_path 你修改过吗？

**Comment by happyfish100** [comment]
如果修改了 base_path，需要同步修改 sytemd配置文件 fdfs_trackerd.service中的 PIDFile

**Comment by oxygengas** [comment]
问题已经解决，谢谢大神




549574553
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "happyfish100/fastdfs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月24日(星期四) 上午10:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [happyfish100/fastdfs] service fdfs_trackerd start 卡死 (Issue #599)





 
如果修改了 base_path，需要同步修改 sytemd配置文件 fdfs_trackerd.service中的 PIDFile
