### ISSUE TITLE
make Fastdfs时报错提示 对‘‘trim’未定义的引用

### ISSUE THREAD

**Issue by caicai123caicai** [happyfish100/fastdfs#601]
../common/fdfs_http_shared.o：在函数‘fdfs_http_get_content_type_by_extname’中： /usr/local/tmp/fastdfs-5.05/client/../common/fdfs_http_shared.c:75：对‘hash_find_ex’未定义的引用 ../common/fdfs_http_shared.o：在函数‘fdfs_http_params_load’中： /usr/local/tmp/fastdfs-5.05/client/../common/fdfs_http_shared.c:280：对‘hash_destroy’未定义的引用 ../common/fdfs_http_shared.o：在函数‘fdfs_http_params_destroy’中： /usr/local/tmp/fastdfs-5.05/client/../common/fdfs_http_shared.c:299：对‘hash_destroy’未定义的引用 ../common/mime_file_parser.o：在函数‘load_mime_types_from_file’中： /usr/local/tmp/fastdfs-5.05/client/../common/mime_file_parser.c:72：对‘hash_init_ex’未定义的引用 /usr/local/tmp/fastdfs-5.05/client/../common/mime_file_parser.c:111：对‘hash_insert_ex’未定义的引用 ../tracker/fdfs_shared_func.o：在函数‘fdfs_load_storage_ids’中： /usr/local/tmp/fastdfs-5.05/tracker/fdfs_shared_func.c:507：对‘trim’未定义的引用

**Comment by happyfish100** [comment]
FastDFS的版本太旧了，建议使用最新版本。
