### ISSUE TITLE
Fastdfs-V6.9.1启动storaged，报错找不到PID

### ISSUE THREAD

**Issue by wshuigao** [happyfish100/fastdfs#602]
大佬你好，我这边出现个问题，求解答。
使用相关版本如下：
**libfastcommon-V1.0.64
libserverframe-V1.1.23
fastdfs-V6.9.1**

我再启动storaged的时候，报错PID找不到。

启动前，我首先进行编辑  `vim /usr/lib/systemd/system/fdfs_storaged.service ` 这个文件
指定PID位置为：`PIDFile=/home/fastdfs/storage/data/fdfs_storaged.pid`
然后执行 `systemctl start fdfs_storaged ` 进行启动，报错：`Job for fdfs_storaged.service failed. See "systemctl status fdfs_storaged.service" and "journalctl -xe" for details.`
接着我执行 `systemctl status fdfs_storaged.service`，查看详细错误，报错如下：
```
12月 03 13:58:42 VM-16-14-centos systemd[1]: Starting FastDFS storaged service...
12月 03 13:58:42 VM-16-14-centos systemd[1]: Can't open PID file /home/fastdfs/storage/da...ry
12月 03 13:58:42 VM-16-14-centos systemd[1]: Daemon never wrote its PID file. Failing.
12月 03 13:58:42 VM-16-14-centos systemd[1]: Failed to start FastDFS storaged service.
12月 03 13:58:42 VM-16-14-centos systemd[1]: Unit fdfs_storaged.service entered failed state.
12月 03 13:58:42 VM-16-14-centos systemd[1]: fdfs_storaged.service failed.
```
我看/home/fastdfs/storage/data/确实没有PID文件，然后就自己创建一个PID文件，但是重新执行启动命令以后，这个文件被删除掉了，接着报错上面的信息

**Comment by happyfish100** [comment]
看一下 storaged.log，应该是启动失败了。

**Comment by wshuigao** [comment]
我去，太蠢了，忘了看这个日志文件了，谢谢大佬

**Comment by wshuigao** [comment]
已解决

**Comment by YogurtOlderMan** [comment]
> 已解决

怎么解决的？我这边也是报pid找不到

**Comment by wshuigao** [comment]
> > 已解决
> 
> 怎么解决的？我这边也是报pid找不到

太久了，我也忘了，但是我之前搞得时候做了个记录，你自己看看有没有吧。https://juejin.cn/post/7177195631985819709
