### ISSUE TITLE
hash_destroy未定义引用

### ISSUE THREAD

**Issue by An-ease** [happyfish100/fastdfs#607]
/usr/bin/ld: ../common/fdfs_http_shared.o: in function `fdfs_http_get_content_type_by_extname':
/root/third/fastdfs-6.03_dev/client/../common/fdfs_http_shared.c:75: undefined reference to `hash_find_ex'
/usr/bin/ld: ../common/fdfs_http_shared.o: in function `fdfs_http_params_load':
/root/third/fastdfs-6.03_dev/client/../common/fdfs_http_shared.c:285: undefined reference to `hash_destroy'
/usr/bin/ld: ../common/fdfs_http_shared.o: in function `fdfs_http_params_destroy':
/root/third/fastdfs-6.03_dev/client/../common/fdfs_http_shared.c:304: undefined reference to `hash_destroy'
/usr/bin/ld: ../common/mime_file_parser.o: in function `load_mime_types_from_file':
/root/third/fastdfs-6.03_dev/client/../common/mime_file_parser.c:72: undefined reference to `hash_init_ex'
/usr/bin/ld: /root/third/fastdfs-6.03_dev/client/../common/mime_file_parser.c:111: undefined reference to `hash_insert_ex'
/usr/bin/ld: ../tracker/fdfs_server_id_func.o: in function `fdfs_load_storage_ids':
/root/third/fastdfs-6.03_dev/tracker/fdfs_server_id_func.c:341: undefined reference to `trim'
collect2: error: ld returned 1 exit status
make: *** [Makefile:59: fdfs_monitor] Error 1

5.12，6.03-dev，6.9.2，6.03版本均出现此问题

**Comment by happyfish100** [comment]
建议使用最新版本6.9.2。
相应地需要使用最新的libfastcommon

**Comment by happyfish100** [comment]
如果安装过很早以前版本的libfastcommon，可能会出现多个libfastcommon版本的问题，
请执行如下命令：/bin/rm -rf /usr/local/lib/libfastcommon.so /usr/local/include/fastcommon
然后再重新编译和安装 FastDFS。

**Comment by An-ease** [comment]
感谢，已经解决，确实是common和dfs版本不匹配问题
