### ISSUE TITLE
springboot3.0.0 initTracker()未执行

### ISSUE THREAD

**Issue by PeterPandora** [happyfish100/fastdfs#609]
springboot3.0.0，项目启动未执行com.github.tobato.fastdfs.domain.conn.TrackerConnectionManager中的initTracker()方法，导致调用fastdfs失败
![image](https://user-images.githubusercontent.com/44386861/209790009-239dd2ed-4c66-41c0-8e65-405cea089f0d.png)

**Comment by happyfish100** [comment]
这个第三方 SDK不够稳定，推荐使用我们官方SDK：fastdfs-client-java
项目地址：https://github.com/happyfish100/fastdfs-client-java

**Comment by xuningnh** [comment]
遇到了同样的问题,也是换成springboot3.0 之后无法初始化了
