### ISSUE TITLE
fastdfs集群文件同步问题

### ISSUE THREAD

**Issue by walawalala123** [happyfish100/fastdfs#610]
情景：两台机器，机器一启storage、tracker；第二台启storage。正常操作上传同步后，手动删除第二台机器的~/storage/data/00/00/下的文件
疑问：能否通过在机器一操作重新触发同步？如果可以能简单说一下操作吗？

**Comment by happyfish100** [comment]
删除部分数据是不会触发同步的；删除所有数据，这样就可以当作一台新的 storage server，FastDFS会自动同步已有文件。

**Comment by walawalala123** [comment]
感谢大佬，后来自己又尝试了一下确实不可以重新触发同步；但是在binlog日志中新增对应的文件操作日志，只要时间戳比同步到其他机器的要晚，重启一下当前storage节点就可以重新触发同步到其他机器，感觉有点类似于文件新增了但是确实可以同步过去。
