### ISSUE TITLE
fastdfs5.05出现cpu暴增

### ISSUE THREAD

**Issue by leiyq123** [happyfish100/fastdfs#611]
在网上有看到博主的针对5.04的回答,但是我在问题区看到5.05也有该问题,想问下现在进行服务升级的话,需要对哪些进行升级,升级后的数据如何保证还能读取,如果重新安装的话,有没有稳定的fastdfs版本和libfastcommon版本号,最好是配套版本,谢谢

**Comment by happyfish100** [comment]
使用最新版本就可以，升级共享库和程序文件即可，完全平滑升级。
