### ISSUE TITLE
大佬您好，请教一下关于fastdfs的binlog日志相关问题

### ISSUE THREAD

**Issue by walawalala123** [happyfish100/fastdfs#612]
大佬您好，请教一下
1、时间戳是怎么来计算转换成现实生活中的时间呢（1673579687==>几点几分类似于这种转换)
2、我尝试在fastdfs的storage节点的data目录中添加几个文件，然后把数据插入到binlog日志中时间戳比最后一次同步的时间要大，然后重启一下主节点的storage的服务有时候可以马上同步到其余节点，但是有时候就要等很长时间才会同步，时间戳对这种违规操作也有影响吗？
3、进行了上述违规操作之后，storage/data/sync/ip.mark中的until_timestamp=字段不再更新，也是受这个影响吗？

**Comment by happyfish100** [comment]
1. LInux使用命令示例：
   date -d @1673579687

2. FastDFS文件同步依赖binlog，其中时间戳这个字段很关键，不要手工修改binlog文件

3. until_timestamp记录第一次全量同步时需要同步到的时间戳，这个值一旦生成就不会改变

**Comment by walawalala123** [comment]
好滴好滴，非常感谢大佬
