### ISSUE TITLE
请问一下大佬，什么样的文件才是有效的appender file

### ISSUE THREAD

**Issue by TEDTO** [happyfish100/fastdfs#618]
我在使用modify_file()的时候 返回22 storage的日志 报了xxxx.log is not a valid appender file 请问该如何解决或者说如何正确使用这个方法

**Comment by TEDTO** [comment]
ERROR - file: storage_service.c, line: 4830, client ip: 10.45.137.190, file: M00/00/00/rBBsPmPzMp6AN9tOAAAAA4hIY9I383.log is not a valid appender file, file size: -9207649785081757693

**Comment by happyfish100** [comment]
需要使用 upload_appender接口上传文件，而不是普通的 upload_file接口。

**Comment by TEDTO** [comment]
十分感谢大佬的快速回复！也就是说，使用upload_appender_file上传的文件才能够使用modify_file()和append_file()操作

**Comment by happyfish100** [comment]
> 十分感谢大佬的快速回复！也就是说，使用upload_appender_file上传的文件才能够使用modify_file()和append_file()操作

是的。
