### ISSUE TITLE
多个Trackerserver有一部分挂了，Storage重启失败

### ISSUE THREAD

**Issue by Hintic** [happyfish100/fastdfs#619]
多个Trackerserver有一部分挂了，Storage重启失败，进程直接被杀死，按理说应该只要有tracker server存活，storage就能重启成功的？因为线上不可能保证所有tracker都存活，但是现在只要有tracker挂了，storage重启就会失败，这个合理吗?

**Comment by happyfish100** [comment]
应该是已知的bug，最新版本已经解决了，请升级FDFS到 v6.9.4。

**Comment by Hintic** [comment]
谢谢作者，新版本确实解决了，能告知是在哪个版本解决的，以及大致的原因吗

**Comment by happyfish100** [comment]
6.9.2修复的，git log如下：

commit ab1c27c197129d00d1fdcaba708a8f1d4d341f9d
Author: YuQing <384681@qq.com>
Date:   Fri Dec 16 16:00:40 2022 +0800

    bugfixed: log connection ip_addr and port correctly
