### ISSUE TITLE
请问如果FDFS_MAX_SERVERS_EACH_GROUP超过32 会对 整个应用有很大影响吗？

### ISSUE THREAD

**Issue by Mr-miao** [happyfish100/fastdfs#621]
我们实际生产的时候遇到一个问题：

希望在一个group里放36~40个storage，每个storage分别在一台物理服务器上。

但是实际运行时Tracker报了超出分组长度的限制的异常

由于还没有通读源码，所以想问问，如果我们直接修改FDFS_MAX_SERVERS_EACH_GROUP，是否对应用会有影响？

还望能得到大佬们的解答，万分感谢

**Comment by happyfish100** [comment]
修改后需要重新编译和安装，对应用应该没有影响。
