### ISSUE TITLE
6.0.8 tracker服务崩溃

### ISSUE THREAD

**Issue by hunday** [happyfish100/fastdfs#622]
项目中更改了FDFS_MAX_SERVERS_EACH_GROUP这个值，并完成了tracker与部分storage服务器的更新，还有一部分storage未更新。
导致偶发性的出现tracker服务应用崩溃。
在一次崩溃时tracker中日志只记录到
ERROR - file: tracker_mem.c, line: 6224, get index of storage 服务器IP fail!!!

想请教一下作者，到这tracker崩溃有可能的原因的是哪些。

**Comment by happyfish100** [comment]
建议升级到最新的 v6.9.4

**Comment by happyfish100** [comment]
升级到最新的 v6.9.4即可解决这个问题。
