### ISSUE TITLE
make fastdfs-nginx-module问题

### ISSUE THREAD

**Issue by lushangpeng** [happyfish100/fastdfs#624]
麻烦大佬拨冗帮忙解答一下

Centos8，
nginx1.22.1或nginx1.23.2

按照wiki使用了yum安装
rpm -ivh http://www.fastken.com/yumrepo/el8/noarch/FastOSrepo-1.0.0-1.el8.noarch.rpm
yum install fastdfs-server fastdfs-tool fastdfs-config -y
yum install git gcc gcc-c++ make automake autoconf libtool pcre pcre-devel zlib zlib-devel openssl-devel wget vim -y
安装后，在编译安装fastdfs-nginx-module时报错：

```shell
In file included from /fastdfs-nginx-module/src/ngx_http_fastdfs_module.c:6:
/fastdfs-nginx-module/src/common.c:26:10: 致命错误：fastdfs/fdfs_define.h：没有那个文件或目录
 #include "fastdfs/fdfs_define.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
编译中断。
make[1]: *** [objs/Makefile:1206：objs/addon/src/ngx_http_fastdfs_module.o] 错误 1
make[1]: 离开目录“/nginx-1.23.2”
make: *** [Makefile:10：build] 错误 2
```

**Comment by happyfish100** [comment]
需要先编译和安装 fastdfs

**Comment by lushangpeng** [comment]
非常感谢大佬。
