### ISSUE TITLE
最新的6.9.5版本 fdfs_monitor /etc/fdfs/storage.conf 命令查看状态version = 6.9.4

### ISSUE THREAD

**Issue by gecahos** [happyfish100/fastdfs#642]
更新了6.9.5版本，但用命令
fdfs_monitor /etc/fdfs/storage.conf 
查看状态version = 6.9.4

**Comment by happyfish100** [comment]
代码中的版本后来改了并重新打包。如果是装包方式的，重新安装一下即可。

**Comment by gecahos** [comment]
@happyfish100 我刚才又试一下了， 用master已经是能显示正确版本了。  但我用releases里的不管zip包还是tar包，都是6.9.4。不知道是不是我电脑的问题。这个麻烦大神再看看，如果确实releases包里显示有点小问题，您方便的话能重新发布一个新releases包吗？我们这边要求只允许用releases版本。

**Comment by happyfish100** [comment]
感谢反馈，已经重新生成 V6.9.5的tag了。

**Comment by gecahos** [comment]
已部署新的tag包，非常完美。感谢大神！
