### ISSUE TITLE
关于tracker的配置参数reserved_storage_space使用上有几个疑问，望大佬解答

### ISSUE THREAD

**Issue by heshc** [happyfish100/fastdfs#654]
FastDFS v6.04
1、fastdfs集群，两个tracker两个storage，若tracker中reserved_storage_space设置的百分比不一样时，storage是不是取最大的那个百分比
2、当tracker中reserved_storage_space设置具体大小时，如2G，重启集群后，通过查看日志，tracker的参数取值正常，但storage中reserved_storage_space取的是0MB，是否设置具体大小有问题？如下截图
![image](https://github.com/happyfish100/fastdfs/assets/35207972/2f16c7bc-732a-4207-beda-df17dc0143da)
![image](https://github.com/happyfish100/fastdfs/assets/35207972/9ed8173f-1ac9-4e27-ac4d-0fbb839546de)

**Comment by happyfish100** [comment]
你升级到最新的 FastDFS v6.9.5，然后看看有没有什么问题。

**Comment by heshc** [comment]
升级到最新版本v6.9.5后问题解决
