### ISSUE TITLE
storage启动是提示tracker内网IPv6（fe80开头）地址无效的参数Invalid argument

### ISSUE THREAD

**Issue by EggSoup** [happyfish100/fastdfs#680]
我使用最新支持IPv6特性的源码进行编译安装，根据wiki指导修改好配置启动tracker和storage服务，发现当storage.conf中配置的为IPv6内网地址（fe80开头）时，启动storage服务会连接不上，提示Invalid argument，如果配置的是互联网IPv6地址（2409开发）则可以成功。
以下是错误提示日志：
<img width="830" alt="fastdf_storaged" src="https://github.com/happyfish100/fastdfs/assets/26017026/4c8cb9a2-5edb-410e-953f-6345a4ca9da5">
以下是storage.conf配置地址：
<img width="324" alt="fastdfs2" src="https://github.com/happyfish100/fastdfs/assets/26017026/b1dae81b-df60-4ec2-acfb-b0be4fef1da7">

**Comment by EggSoup** [comment]
后来查询资料发现fe80是链路本地地址，理论上是不经过路由通信的，所以网络访问一应该死是不能通过链路本地地址通信，所以在storage服务通过链路本地地址去请求tracker服务时回提示错误。

**Comment by happyfish100** [comment]
局域网中可以使用 fe80::打头的IPv6地址。
经调试发现libfastcommon 中有个 bug，刚才修复了，需要使用最新的 master代码重新编译和安装。
另外， fe80::打头的IPv6地址 后面需要加上 %网络接口名，比如：fe80::d85d:4b0a:1e5b:212c%en0，这样才能用于建连。

**Comment by EggSoup** [comment]
好的，我后续试一下，感谢楼主的贡献。
