### ISSUE TITLE
防盗链小需求

### ISSUE THREAD

**Issue by cxx233** [happyfish100/fastdfs#685]
# 背景
当FastDFS开启防盗链后，全局控制。

但有些类型的文件，不需要通过防盗链处理。例如：用户头像。封面。

# 需求事项
在http.conf 中添加个配置。配置后，可以直接通过文件后缀类型进行忽略。类似白名单访问。

**Comment by happyfish100** [comment]
此类定制需要付费，给点辛苦费可以帮你们实现。
有意可以发邮件到邮箱：384681(at)qq.com，然后我们进一步交流。

**Comment by cxx233** [comment]
好的。谢谢作者的回答。也非常感谢FastDFS贡献。
