### ISSUE TITLE
./make.sh报错，错误：‘SFGlobalVariables’没有名为‘min_buff_size’的成员

### ISSUE THREAD

**Issue by liujie-jss** [happyfish100/fastdfs#696]
FastDFS编译时提示./make.sh
tracker_service.c: 在函数‘tracker_deal_server_list_all_groups’中:
tracker_service.c:2911:39: 错误：‘SFGlobalVariables’没有名为‘min_buff_size’的成员
     if (expect_size > g_sf_global_vars.min_buff_size)
                                       ^
tracker_service.c:2913:44: 错误：‘SFGlobalVariables’没有名为‘max_buff_size’的成员
         if (expect_size <= g_sf_global_vars.max_buff_size)
                                            ^
tracker_service.c:2929:37: 错误：‘SFGlobalVariables’没有名为‘max_buff_size’的成员
                     g_sf_global_vars.max_buff_size);
                                     ^
make: *** [tracker_service.o] 错误 1
![error](https://github.com/happyfish100/fastdfs/assets/51060830/b6998643-2ea8-41a0-b74a-4523010e2a17)

使用版本是目前拉到的最新
这块具体是哪个模块引起的？

**Comment by liujie-jss** [comment]
![Uploading Snipaste_2024-02-26_12-21-19.png…]()

**Comment by happyfish100** [comment]
抱歉，libserverframe升级后，fastdfs做了适配忘记提交。
刚才把代码提交了。

**Comment by liujie-jss** [comment]
> 抱歉，libserverframe升级后，fastdfs做到了忘记提交。 刚才把代码提交了。

感谢，刚试了，可以正常使用了
