### ISSUE TITLE
when upload file comes recvStorageInfo pkgLen 70 invaild

### ISSUE THREAD

**Issue by FunkyYang** [happyfish100/fastdfs#703]
server version:
fdfs_trackerd V6.12.1
fdfs_storaged V6.12.1

use fast dfs for go client,and receive 
```recvStorageInfo pkgLen 70 invaild```
what happend?

**Comment by happyfish100** [comment]
the length of IP address changed from 16 to 46 for IPv6 since FDFS V6.11

**Comment by FunkyYang** [comment]
solved .I copy /etc/fdfs/client,.conf fot test.it should be conf format error

**Comment by FunkyYang** [comment]
I use IPV4 for test,this error is still exists

**Comment by FunkyYang** [comment]
it seems the reply from server not compatible

**Comment by happyfish100** [comment]
you should change the length of IP address from 16 to 46 in FastDFS protocol

**Comment by FunkyYang** [comment]
other questions 

receive from server response,the protocol format may be error,
```
	if _, err := tcpConn.Read(buf); err != nil {
		return err
	}
	// 通信协议详情地址： https://mp.weixin.qq.com/s/lpWEv3NCLkfKmtzKJ5lGzQ
	// 响应body：
	//@group_name：16字节字符串，组名
	//@ip_addr：15字节字符串， storage server IP地址
	//@port：8字节整数，storage server端口号
	//@store_path_index：1字节整数，基于0的存储路径顺序号
	log.Printf("buff:%s", string(buf))
```
```
buff:group1          192.168.1.89                                       Y� 
```
I don't see port param in reponse ？why？

**Comment by happyfish100** [comment]
the port is binary format (not readable digit).

**Comment by Yancy0220** [comment]
请问怎么解决的？
