### ISSUE TITLE
fdfs部署 服务器配置问题请教，swap 内存是否需要关闭 ？

### ISSUE THREAD

**Issue by yangxiRespect** [happyfish100/fastdfs#707]
目前想生产搭建 fdfs 集群，服务器内存 48g 压测时发现 在内存空间足够的时候，swap 内存 占用很高。
想关闭 swap 内存 ，不知道会不会对 fdfs 服务 造成影响。
![WechatIMG3539](https://github.com/happyfish100/fastdfs/assets/30545616/1d590072-bee7-473f-a97d-884f7bcbaa90)

**Comment by happyfish100** [comment]
机器内存足够的情况下，完全可以关闭swap

**Comment by yangxiRespect** [comment]
关闭swao后服务正常
