### ISSUE TITLE
fastdfs集群容量问题

### ISSUE THREAD

**Issue by ppry123** [happyfish100/fastdfs#717]
我按照wiki的安装步骤部署了一个3台主机的集群，每台都启动了tracker+storage，通过/usr/bin/fdfs_monitor /etc/fdfs/storage.conf查看集群的disk total space并不是3台相加而是和单个服务器容量一样，测试了上传文件好像看起来每台主机都上传了一份相同的副本，请问下大佬应该怎么配置才能实现3台容量相加的效果

**Comment by happyfish100** [comment]
那就采用单副本，这样就没有冗余了。

**Comment by ppry123** [comment]
> 那就采用单副本，这样就没有冗余了。

具体怎么配置呀大佬，请不吝赐教

**Comment by ppry123** [comment]
现在每个机器我弄了一个group，3台都配了nginx，看起来是解决了
