### ISSUE TITLE
通过外网地址上传文件时，tracker.service.c, line1289 报错

### ISSUE THREAD

**Issue by ZHAIMZ** [happyfish100/fastdfs#718]
报错信息如下：file: tracker_service.c, line: 1289, client ip addr: 60.208.85.83, operation not supported。
![微信图片_20240806111809](https://github.com/user-attachments/assets/0c11b9e4-77e3-48db-83aa-fab8eb8adefa)

**Comment by JL103312** [comment]
我也遇到了，java连接 初始化时候 报错空指针，去看日志报错 operation not supported ，你是怎么解决的呢

**Comment by JL103312** [comment]
找到原因了是版本不匹配的问题 ： 切换到fdfs-client-java  1.30-SNAPSHOT  版本后成功解决
