### ISSUE TITLE
Stroage 配置了 bind_addr，但是上传文件时获取的 storage 是本机的另一个 ip

### ISSUE THREAD

**Issue by tigerkin-dz** [happyfish100/fastdfs#730]
stroage.conf
![image](https://github.com/user-attachments/assets/2905c606-31f6-475a-98fd-128d60348494)

tracker.conf
![image](https://github.com/user-attachments/assets/dd47d4f6-0db9-416c-8eb6-4765a9799e30)

client.conf
![image](https://github.com/user-attachments/assets/a6bc637c-78d9-4a3f-8678-2de1df8af324)

结果
![image](https://github.com/user-attachments/assets/c79d6037-5a83-43ea-bc69-ad5ecccb1e45)
![image](https://github.com/user-attachments/assets/76ff7c46-a946-422c-b98f-cd6048c721e9)

**Comment by happyfish100** [comment]
另外一个 IP 也是 10.216.176 这个网段的吗？

**Comment by tigerkin-dz** [comment]
是的

**Comment by tigerkin-dz** [comment]
这台机器有两个ip，分别是118.118.116.206和10.216.176.1，我配置的ip是后者，但是上传的时候确获取到前者

**Comment by tigerkin-dz** [comment]
我尝试过把10.216.176.1替换成118.118.116.206，是没有问题的，能正常上传文件。但是我们目前的环境需要配置10.216.176.1，客户机才能正常连接 使用

**Comment by happyfish100** [comment]
你们这个环境比较特殊。请问10.216.176.1 是用作网关吗？

**Comment by happyfish100** [comment]
可以使用 storage id 特性，在 storage_ids.conf 中配置，详情参见配置示例文件。

**Comment by tigerkin-dz** [comment]
> 你们这个环境比较特殊。请问10.216.176.1 是用作网关吗？

10.216.176.1 是我们基于 tinc 搭建的一个局域网分配的ip，也是为了访问内部服务器临时做的应对方式。

**Comment by tigerkin-dz** [comment]
> 可以使用 storage id 特性，在 storage_ids.conf 中配置，详情参见配置示例文件。

storage_ids.conf
![image](https://github.com/user-attachments/assets/bb872aa4-ba24-4193-8796-85e0cbf3ee6f)

tracker.conf
![image](https://github.com/user-attachments/assets/7ecb0801-c8ac-40d8-87a8-af15761541f3)

storage.conf
![image](https://github.com/user-attachments/assets/b0ef79fd-cf2a-497b-9d96-56216cb48021)

结果
![image](https://github.com/user-attachments/assets/cd6b92df-53ad-443a-b8cb-7ede6aeaa1cc)

**Comment by tigerkin-dz** [comment]
我这里是还有什么地方没有配置好吗

**Comment by tigerkin-dz** [comment]
> 我这里是还有什么地方没有配置好吗

![image](https://github.com/user-attachments/assets/b343ae97-14b8-4113-b8d5-83bc55aab300)

**Comment by happyfish100** [comment]
server_id 要用配置在 storage_ids.conf 中的数字 id。

**Comment by happyfish100** [comment]
另外，把 storage_servers_new.dat 这个文件中的 IP 地址手工修改一下。

**Comment by tigerkin-dz** [comment]
> 另外，把 storage_servers_new.dat 这个文件中的 IP 地址手工修改一下。

storage_servers_new.dat
![image](https://github.com/user-attachments/assets/60236512-e6a4-4886-8f94-2b82fd4b54a1)

storage.conf
![image](https://github.com/user-attachments/assets/a76819b1-3e1f-492c-bcfa-825e8c97f0cb)

重启 tracker 出现异常
![image](https://github.com/user-attachments/assets/caac2de1-d27f-4a78-93b5-f22b75044d1a)

**Comment by tigerkin-dz** [comment]
> storage_sync_timestamp.dat 中，需要把第二列的 IP 地址修改为 storage server id。

感谢耐心回复，问题已解决
