### ISSUE TITLE
fastdfs开启token认证的时候长期不失效如何解决

### ISSUE THREAD

**Issue by hujie5592427** [happyfish100/fastdfs#91]
http.default_content_type = application/octet-stream
http.mime_types_filename=mime.types
http.anti_steal.check_token=true
http.anti_steal.token_ttl=900
http.anti_steal.secret_key=FastDFS1234567890
http.anti_steal.token_check_fail=/var/fastdfs/conf/anti-steal.jpg

上面是我的http.conf内容，开启后防盗链是生效了，但是都一天了还是不失效如何解决**

**Comment by happyfish100** [comment]
HTTP方式确认是通过FDFS扩展模块访问的？

**Comment by hujie5592427** [comment]
@happyfish100 我用的是FDFS扩展模块，现在已经生效了，重启一下nginx就生效了，谢谢
